### PR TITLE
Capture git submodule changes in nightly builds

### PR DESCRIPTION
**Pull request by vraravam**
#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has _stopped working_ or is _working incorrectly_, please log the bug [here](https://github.com/getferdi/recipes/issues)
2. If you are requesting support for a **new service** in Ferdi, please log it [here](https://github.com/getferdi/recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdi, but to get new recipes between Ferdi releases, this documentation is quite useful.)
4. Please consider supporting Ferdi!
  👉 https://github.com/sponsors/getferdi
  👉 https://opencollective.com/getferdi/donate
5. Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change
Capture git submodule changes in nightly builds

#### Motivation and Context
Looks like the nightly builds are not capturing the latest version of the `recipes` submodule. This is an attempt to try and fix the process so that it picks up all the pending changes in the submodule.

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`npm run prepare-code`)
- [x] `npm test` passes
- [ ] I tested/previewed my changes locally

### CODE REVIEW

**Comment by vraravam** [comment]
Trying to fix this: https://github.com/getferdi/recipes/pull/787#issuecomment-997697307

**Review by mhatvan — APPROVED** [review]
I also think there is something not right with submodules. Whenever I fetch the latest develop and update the submodule, `oh-my-zsh` still shows me that I am not fully up to date. 

Let's see if this fixes it.

**Comment by vraravam** [comment]
Signing off of ferdi - can't work with an autocratic maintainer.
Screenshot 2021-12-21 at 7 18 57 PM

**Comment by BKPepe** [comment]
@kytwb Woah, that's not very pleasant. This is not a very good way to communicate with external contributors. It seems you had a bad day, but still, we should be more friendly to each other. You came out of nowhere and acted like a boss. Everyone can have their opinions and I think it's the team who decides here.  Am I thinking if you are talking to sponsors like this?

**Pull request closed without merging**
