### PR TITLE
Adding a proxy settings component to be used in service settings, server settings and advanced settings

### PR DESCRIPTION
**Pull request by saruwman**
### Checklist:

- [ ] My pull request is properly named
- [ ] The changes respect the code style of the project (`$ npm run lint`)
- [ ] I tested/previewed my changes locally

### CODE REVIEW

**Comment by saruwman** [comment]
#771 
#587

**Comment by Nokia808** [comment]
Dear please we need:
- none
- http proxy
- SOCKS proxy

Also, there is problem with Tor: when user set on Tor proxy (127.0.0.1:9050) all the udp connection must disabled ! How you will manage this issue ? Is it suitable for Ferdi to make all udp connections disabled when user select any thing other than "none" ? This is the approach of qTox (serverless skype like messenger), but I'm not sure if this suitable for nature of Ferdi or not. If not, then I see the best solution is to make preconfigured Tor setting in the choices so that when user select this choice then udp connections will automatically disabled. If this solution considered then we should have the following options:
- none
- Tor
- custom
& if user select "custom" then she/he will has the following options:
- Type of proxy (HTTP proxy, SOCKS proxy)
- address
- port

Other solution is to give independent option (in the proxy setting or in independent place) to enable/disable udp connections .....

Best.

**Comment by Nokia808** [comment]
This PR is important because it add a significant feature to Ferdi, so please keep it open & do not close it. 

I'm not the author of this PR, but it solve an issue that I already post it & linked here in this thread.

**Comment by vantezzen** [comment]
This PR was is marked as stale because the author hasn't made any activity in 3 months. We won't close this PR, the stale tag only helps us to keep on overview of active issues and PRs and those that don't seem to be no longer maintained or have lost traction.

**Pull request closed without merging**
