### PR TITLE
Indirect notification icons in tray and tabs

### PR DESCRIPTION
**Pull request by FeikoJoosten**
Currently Ferdi doesn't differentiate between direct and indirect notification badges.

Note, this is pretty much a copy pasta from #590, but with some extra functionality.

### Description

* All Platforms- Add an icon used for showing indirect notifications in the taskbar. This is just a copy of the notifications icon, but with a blue(#0088cc) color (like slack, google chat etd)
* All Platforms - Replace the red color used for indirect notifications in tabbed view for a service to
#0088cc (Blue) color

### Motivation and Context

This PR is to address [#583](https://github.com/getferdi/ferdi/issues/583)

### How Has This Been Tested?

* This has been tested on Windows 10 on a Ferdi dev environment.

### Screenshots (if appropriate):
Indirect and direct notification bubble in the side bar.
image
Indirect notification bubble on the tray icon.
image

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist:

- [X] My code follows the code style of this project (run `$ yarn lint`).

### CODE REVIEW

**Comment by FeikoJoosten** [comment]
@kytwb As said before. Here you go.

**Comment by kytwb** [comment]
@FeikoJoosten Thank you so much for your contribution! Could we just review the workflow a bit and proceed as described in https://github.com/getferdi/ferdi/pull/590#issuecomment-615876635? Like this, you will iterate on top of @mahadevans87 and @sampathBlam iteration and it will show in the logs 🙏 Thank you! Happy to assist if needed!

**Comment by FeikoJoosten** [comment]
Ah yes, my bad. Would be a bit of a nasty move to simply ignore their contributions. That wasn't my intention. My bad 😅. If I understand it correctly, I should be able to create a PR on @mahadevans87 branch. Then my changes will be stacked on top of his. And from there, he can create a PR to be merged here right?

**Comment by kytwb** [comment]
@FeikoJoosten No worries, I have to admit git workflows can get a bit tricky, but it's a good opportunity for us to practice! 🙏 I saw you did the pull request in https://github.com/Room4O4/ferdi/pull/1, it should land in #590 once merge by someone at @Room404 😄🙏

**Comment by FeikoJoosten** [comment]
I haven't used Git in ages either. Been using SVN lately. And before that used Perforce a lot. So it's been a while. Had to catch up on a lot of things hehe. But alright. I guess I'll close this. As this seems like a duplicate PR.

**Pull request closed without merging**
