### PR TITLE
Add option to start ferdi in tray

### PR DESCRIPTION
**Pull request by jereksel**
This PR implements #288 

### Description
When system tray is enabled, new option is shown `Start minimized`.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist:

- [ ] My code follows the code style of this project (run `$ yarn lint`).

### CODE REVIEW

**Comment by jereksel** [comment]
Hi, this is my first PR in this project and I have issues with 2 things:
1. How can I add default translation in all languages.
2. I've added switch, but it only works on way - I can enable it, but later I can't disable it.

**Comment by vantezzen** [comment]
> 1. How can I add default translation for all languages?
Run `npm run prepare-code`, this will add it to the english language files. After your PR gets merged, CrowdIn will add all other translations.

> 2. I've added switch, but it only works one way - I can enable it, but later I can't disable it.
Looks like you already fixed this? At least now it seems to work fine.

**Comment by jereksel** [comment]
Weird, switch is working fine now - maybe my DB got corrupted or something.

**Comment by jereksel** [comment]
Don't know why appveyor is failing - it's failing on packaging

**Comment by vantezzen** [comment]
Restarted the build and now its working.
Is the PR ready to be merged?

**Comment by jereksel** [comment]
Yep, but I've tested it only on Linux - I don't have any Macs

**Comment by vantezzen** [comment]
I've tested it on mac and it seems to work.

**Pull request merged**
