### PR TITLE
Release 5.5.0-gm.2

### PR DESCRIPTION
**Pull request by kytwb**
For https://github.com/getferdi/ferdi/issues/536. 

I also took the initiative to bump minor/patch on Electron as to potentially fix some crashes. 
Related changelogs:

https://github.com/electron/electron/releases/tag/v8.2.0
https://github.com/electron/electron/releases/tag/v8.2.1
https://github.com/electron/electron/releases/tag/v8.2.2
https://github.com/electron/electron/releases/tag/v8.2.3

### CODE REVIEW

**Comment by kytwb** [comment]
I have to get back to work for now @vantezzen 🙏 Feel free to take over if you have time before me, otherwise I will continue after work. Thank you!

**Comment by kytwb** [comment]
Re-tagged 5.5.0-gm.2 to include regression fix and latest translations.

**Comment by kytwb** [comment]
@vantezzen good to merge in my opinion; would be good to re-tag to the squash merge commit afterward and re-push the tag to regenerate the release assets.

**Comment by kytwb** [comment]
Making a pull request from the release branch against develop wasn't the smartest choice, but noted for next iteration.

**Comment by kytwb** [comment]
Had forgot one thing during the review (missing spacing between settings tabs) and noticed the initial system notification content on macOS.

**Comment by vantezzen** [comment]
Why was the AppVeyor build stopped?

**Comment by kytwb** [comment]
Re-triggered, my mistake. I was trying to reduce the amount of builds as a lot were triggered (and took note of that via https://github.com/getferdi/ferdi/issues/629).

**Comment by kytwb** [comment]
I need your approval to merge and I can't self approve.

**Pull request merged**
