### PR TITLE
Fix macOS code signing and setup automatic nightly builds

### PR DESCRIPTION
**Pull request by kytwb**
### Description

This pull request fixes the [macOS code signing error](https://travis-ci.org/github/getferdi/ferdi/jobs/727962974#L330) we were experiencing on the release/nightly branches.
It also finishes off setting up fully-automated [nightly releases](https://github.com/getferdi/nightlies/releases).

Nightly builds are triggered by a daily Travis CI cron job. The Travis build takes care of bumping the nightly version up and building macOS/Linux deliverables. It then commits and pushes back the version bump and submodules ref updates to the nightly branch, which triggers the rest of the build on AppVeyor for Windows deliverables. Once AppVeyor is done, the nightly release draft is ready to be published.

### Motivation and Context

The main motivation is to enable the community to iterate faster.

Closes https://github.com/getferdi/ferdi/issues/611.

### Screenshots

[Screen Shot 2020-10-03 at 10 50 00 AM](https://travis-ci.org/github/getferdi/ferdi/jobs/732472877#L1287)

[Screen Shot 2020-10-03 at 10 48 14 AM](https://travis-ci.org/github/getferdi/ferdi/settings)

### Checklist:

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`$ npm run lint`)
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Comment by vantezzen** [comment]
Great PR!

> Nightly builds are triggered by a daily Travis CI cron job

I don't know if building a nightly release daily is necessary though. Ferdi's development doesn't move _that_ fast and I fear that this might also cause problems with AppVeyor's storage quota overflowing again? I'd suggest lowering that down to once a week, WDYT?

**Comment by kytwb** [comment]
@vantezzen I agree that building every day if there is nothing new can be a waste of resources. What do you think of pursuing the nightly build only if there is something new to merge from develop?

**Comment by vantezzen** [comment]
Yes, that sounds good

**Comment by kytwb** [comment]
@vantezzen done.

We would need to merge this pull request for AppVeyor builds to start again as they don't run for branches with open pull requests. We won't open much pull requests from nightly to develop in the future so that is not really a problem.

**Review by vantezzen — APPROVED** [review]

**Pull request merged**
