### PR TITLE
Add configurable hibernation interval after auto-wakeup

### PR DESCRIPTION
**Pull request by jamesandariese**
#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has _stopped working_ or is _working incorrectly_, please log the bug [here](https://github.com/getferdi/recipes/issues)
2. If you are requesting support for a **new service** in Ferdi, please log it [here](https://github.com/getferdi/recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdi, but to get new recipes between Ferdi releases, this documentation is quite useful.)
4. Please consider supporting Ferdi!
  👉 https://github.com/sponsors/getferdi
  👉 https://opencollective.com/getferdi/donate
5. Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change

Add a configurable hibernation timeout used after waking automatically from
hibernate.
Add a splay feature to desynchronize wake times a little and prevent all of your
services from unhibernating at the same time directly after start up.

#### Motivation and Context
When waking from hibernate automatically, the standard hibernation settings
apply for the next hibernation, too.  For example, if you hibernate after 5 minutes 
but want to ensure your notifications are delayed by no more than 1 minute, you
would have to wake up after 1 minute and stay awake for 5 more minutes.  With
this feature, you can sleep after 5 minutes then wake up every minute for 10
seconds (or 1 minute or some other configurable interval).

The goal is to hibernate as much as possible but still get activity badges in a
timely fashion with a configurable sense of "timely".  If that means 1 minute,
you can still benefit from the memory savings of hibernation without needing to
configure your app to hibernate more quickly than you'd like.

```
W = awake period
s = hibernating period

Before:
5m -> 1m (sleep) -> 5m (wake) -> 1m (sleep) -> 5m (wake) -> etc.
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWssssssWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWssssss
After:
5m -> 1m (sleep) -> 1m (wake) -> 1m (sleep) -> 1m (wake) -> etc.
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWssssssWWWWWWssssssWWWWWWssssssWWWWWWssssss
```

To limit the amount of processing done during those 10 seconds, there is an
added splay option which will randomly add 10s to the sleep time.

This example has the following settings
hibernation strategy:          1m
wake up strategy:              1m
wake up hibernation strategy: 10s
splay:                         on
services:                       5

Sample result:

```
WWWWWWssssssWsssssssWssssssWsssssssWssssssWsssssssWssssss
WWWWWWsssssssWsssssssWsssssssWssssssWsssssssWsssssssWssssss
WWWWWWssssssWssssssWssssssWssssssWssssssWsssssssWssssss
WWWWWWsssssssWsssssssWssssssWsssssssWssssssWsssssssWssssss
WWWWWWsssssssWsssssssWsssssssWsssssssWsssssssWsssssssWssssss
```

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`npm run prepare-code`)
- [x] `npm test` passes
- [x] I tested/previewed my changes locally

#### Release Notes
Add configurable hibernation timeout after automatically waking up.

### CODE REVIEW

**Comment by jamesandariese** [comment]
I'm having trouble building this locally.  I'm not entirely sure if it's my own setup or not.  Either way, I moved this to draft and I'm going to let it bake locally for a day or two and maybe promote it to ready if things go okay.

In case anyone knows, two things are interfering with my builds:

---
#### husky

husky fails to install its hooks :

```
npm ERR! code 1                        
npm ERR! path /Users/james/src/github.com/jamesandariese/ferdi/build                                                                                           
npm ERR! command failed
npm ERR! command sh -c is-ci || husky install                                  
```

It doesn't given any output but my current workaround is to run `mkdir .git` after running `npm run build` which lets husky find the .git folder and not give an error.

---

#### node-mac-permissions

node-mac-permissions doesn't install with `npm i` or with `npm i node-mac-permissions`.  The result is that the built app crashes on mac with sigabrt.  I work around that by setting the version to >0 (instead of the pinned git commit) and running again which installs 2.2.0 and works but obviously will continue breaking on non-macs.

```
npm ERR! gyp info spawn make                                                                                                                                   
npm ERR! gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]                                                                                     
npm ERR! warning: /Library/Developer/CommandLineTools/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file member
s in the library define global symbols)                                                                                                                        
npm ERR! ../permissions.mm:13:9: fatal error: 'Storekit/Storekit.h' file not found                                                                             
npm ERR! #import <Storekit/Storekit.h>                                                                                                                         
npm ERR!         ^~~~~~~~~~~~~~~~~~~~~                                                                                                                         
npm ERR! 1 error generated.                                                                                                                                    
npm ERR! make: *** [Release/obj.target/permissions/permissions.o] Error 1                                                                                      
```

I suspect this is because I have xcode cli tools and not xcode itself.  I'll be installing xcode when I've got some more time and seeing if that resolves it but if anyone knows either way, that'd be excellent.

---

I expect I can resolve these things, at least locally, without assistance but if these are known issues or if anyone has any guesses as to what's wrong with my environment, I'd love to hear about it.

Thanks and I'll be back in a while with some progress, I hope :smile:

**Comment by jamesandariese** [comment]
alright, I don't know what's going on with husky but I figured out the root cause of the storekit issue.  it's because I was silly and thought case-sensitive macos was a good idea in 2022.  it still isn't.

I've been running this version of the code for the past day, using it actively, and I'm happy with it.

**Comment by jamesandariese** [comment]
alright, I don't know what's going on with husky but I figured out the root cause of the storekit issue.  it's because I was silly and thought case-sensitive macos was a good idea in 2022.  it still isn't.

I've been running this version of the code for the past day, using it actively, and I'm happy with it.

**Comment by kytwb** [comment]
Thanks for your contribution and ownership.

@all-contributors please add @jamesandariese for code

**Comment by jamesandariese** [comment]
I've fixed the lint error, I believe, and noticed prettier didn't seem to actually change the file on my system.  I ran it by hand on the file after trying a couple times with npm run reformat-files`.  I didn't see the lonely if error in pre-commit before but I can repro it now.

```bash
james@Jamess-MBP ferdi % git checkout 9c46b89a
Note: switching to '9c46b89a'.

You are in 'detached HEAD' state. You can look around, make experimental
.
.
.
HEAD is now at 9c46b89a Merge branch 'getferdi:develop' into feature/tinywake
james@Jamess-MBP ferdi % node_modules/.bin/eslint --plugin unicorn src/stores/ServicesStore.js --quiet

/Users/james/src/github.com/jamesandariese/ferdi/src/stores/ServicesStore.js
  1078:8  error  Unexpected `if` as the only statement in a `if` block without `else`  unicorn/no-lonely-if

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

james@Jamess-MBP ferdi % git checkout feature/tinywake
Previous HEAD position was 9c46b89a Merge branch 'getferdi:develop' into feature/tinywake
Switched to branch 'feature/tinywake'
Your branch is up to date with 'origin/feature/tinywake'.
james@Jamess-MBP ferdi % node_modules/.bin/eslint --plugin unicorn src/stores/ServicesStore.js --quiet
```

Unsure what's going on with these things but I am happy to blame my filesystem format (for now) since [not] ignoring case when the other is expected can yield strange and unexpected problems.  I'll be fixing that before trying to make any more contributions to get my environment more in line with the expected defaults.

Sorry for the commit churn!

**Pull request merged**
