### PR TITLE
Add 5.5.0-gm and 5.5.0 changelog

### PR DESCRIPTION
**Pull request by vantezzen**
This PR adds the changelog for v5.4.4-gm and additionally adds a new "link-readme" script to automatically link issues and users inside the README to GitHub. It will also now add a link to the contributors who created the features linked in README.md

I'll leave this PR as a draft while the feature list for 5.4.4-gm is not released

### CODE REVIEW

**Comment by kytwb** [comment]
@vantezzen should we go for 5.5.0 directly?

**Comment by vantezzen** [comment]
You mean releasing 5.5.0 now? Sounds good.

**Comment by kytwb** [comment]
@vantezzen I meant skip 5.4.4-gm and stable. Let's go for 5.5.0 directly then! 💪

**Comment by vantezzen** [comment]
Hmm, I'd still suggest releasing 5.5.0-gm first as we do have many features added since then - at least for the contributors to test for a few days. We can release the gm now and then release the final version with the remaining PRs included.

**Comment by kytwb** [comment]
@vantezzen understood and agreed! 🙏

**Pull request merged**
