### PR TITLE
upgraded react-router version

### PR DESCRIPTION
**Pull request by SarveshLimaye**
### Open todos

- might be able to finish up, but probably is interconnected with `mobx-router`, which would need upgrade, which would require `mobx` to get upgrade, etc.
- `react-router` v6 stable was released in the mean time

#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has _stopped working_ or is _working incorrectly_, please log the bug [here](https://github.com/getferdi/recipes/issues)
2. If you are requesting support for a **new service** in Ferdi, please log it [here](https://github.com/getferdi/recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdi, but to get new recipes between Ferdi releases, this documentation is quite useful.)
4. Please consider supporting Ferdi!
  👉 https://github.com/sponsors/getferdi
  👉 https://opencollective.com/getferdi/donate
5. Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change
Upgraded react router version to v4.

#### Motivation and Context
#2040 
#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`npm run prepare-code`)
- [x] `npm test` passes
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Comment by SarveshLimaye** [comment]
@mhatvan @vraravam I have made the suggested changes . Can you pls review my pr now .

**Comment by mhatvan** [comment]
> @mhatvan @vraravam I have made the suggested changes . Can you pls review my pr now .

All of my comments are not fulfilled yet.

**Comment by mhatvan** [comment]
I checked out the branch locally and it seems that the application does not even start:
Screenshot from 2021-10-11 08-47-53

**Comment by mhatvan** [comment]
> @mhatvan It was working fine before. Don't know what happened now. I also faced this same issue before . I have mentioned that in the issue. What should we do now ?

I pushed another commit which upgrades `react-router-dom` to latest, that fixes that application start issue.

Unfortunately, when opening the settings screen or adding a new service, then the application crashes due to our outdated `react-jss` dependencies, e.g. `Warning: Failed context type: The context __THEMING__ is marked as required in Jss(ErrorBoundary), but its value is undefined.`

I started https://github.com/getferdi/ferdi/pull/1788 a while ago, but it requires touching countless files.

I will check if we can find a solution to merge this PR, otherwise it will have to wait unfortunately until https://github.com/getferdi/ferdi/pull/1788 (will continue that one right away)

**Comment by SarveshLimaye** [comment]
> > @mhatvan It was working fine before. Don't know what happened now. I also faced this same issue before . I have mentioned that in the issue. What should we do now ?
> 
> I pushed another commit which upgrades `react-router-dom` to latest, that fixes that application start issue.
> 
> Unfortunately, when opening the settings screen or adding a new service, then the application crashes due to our outdated `react-jss` dependencies, e.g. `Warning: Failed context type: The context __THEMING__ is marked as required in Jss(ErrorBoundary), but its value is undefined.`
> 
> I started #1788 a while ago, but it requires touching countless files.
> 
> I will check if we can find a solution to merge this PR, otherwise it will have to wait unfortunately until #1788 (will continue that one right away)

So I guess the application start issue was due react-router-dom v4. No problem even if the pr has to wait.

**Comment by vraravam** [comment]
@SarveshLimaye - I have force pushed the latest code into your branch while trying to resolve conflicts from the `develop` branch. Could you please keep this PR updated from time-to-time? If it lags too far behind, then unblocking becomes a nightmare.

**Comment by vraravam** [comment]
> I started #1788 a while ago, but it requires touching countless files.

#1788 has now been superseded by #2092

**Comment by SarveshLimaye** [comment]
> @SarveshLimaye - I have force pushed the latest code into your branch while trying to resolve conflicts from the `develop` branch. Could you please keep this PR updated from time-to-time? If it lags too far behind, then unblocking becomes a nightmare.

Yeah sure thanks for updating the branch 😄

**Comment by vraravam** [comment]
@SarveshLimaye - please check why the builds are all broken - it might be due to a bad conflict resolution. Previously, the builds were running fine, but the app was not starting up. Now, it seems worse

**Comment by vraravam** [comment]
Is this superceded by #2299 ?

**Comment by mhatvan** [comment]
> Is this superceded by #2299 ?

Might be, I still have to see the implications. I would prefer to keep that PR small, but it might not be avoidable due to `mobx-react-router` dependency.

**Pull request closed without merging**
