### PR TITLE
[Franz catchup] Use a newer maintained module to trigger and capture permissions on macos.

### PR DESCRIPTION
**Pull request by vraravam**
### Motivation and Context
`mac-screen-capture-permissions` was unmaintained. This new package expose more functionality (and this is what Franz has moved to).

### Checklist:

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`$ npm run lint`)
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Comment by kris7t** [comment]
Fails for me with

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Module did not self-register: '/home/kris/urandom/ferdi/node_modules/node-mac-permissions/build/Release/permissions.node'.
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (/home/kris/urandom/ferdi/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/home/kris/urandom/ferdi/node_modules/node-mac-permissions/index.js:1:40)
```

it seems we have to make the dependency somehow conditional on running on a mac, or at least load it conditionally only if we're on a mac.

**Comment by vraravam** [comment]
@kris7t - could you please check if this works for linux now?

**Comment by vraravam** [comment]
nope - doesn't work - reverting the last commit,

**Comment by vraravam** [comment]
Abandoning this PR. Will review if we need to resurrect this later.

**Comment by kris7t** [comment]
I was wondering if this would work if we conditionally only loaded the module on a mac, i.e., instead of

```js
import { askForScreenCaptureAccess } from 'node-mac-permissions';
```

we said something like

```js
let askForScreenCaptureAccess;
if (isMac) {
  askForScreenCaptureAccess = require('node-mac-permissions').askForScreenCaptureAccess;
}

**Comment by vraravam** [comment]
@kris7t - I have re-opened this PR - please pull and try with the latest commit. I am doing the same in my local.

**Comment by vraravam** [comment]
I can confirm that the app works on mac (x86). I am typing this message from within Ferdi with the above changes.

**Comment by vraravam** [comment]
@kris7t - once you confirm, I might have to create a new PR - since this one seems to not want to reopen.

**Comment by kris7t** [comment]
Still fails for me. But I can get it working like this, i.e., by only loading `macOSPermissions` on a mac:

```diff
diff --git a/src/index.js b/src/index.js
index aea6b146..c4f495cc 100644
--- a/src/index.js
+++ b/src/index.js
@@ -41,7 +41,6 @@ import DBus from './lib/DBus';
 import Settings from './electron/Settings';
 import handleDeepLink from './electron/deepLinking';
 import { isPositionValid } from './electron/windowUtils';
-import askFormacOSPermissions from './electron/macOSPermissions';
 import { appId } from './package.json'; // eslint-disable-line import/no-unresolved
 import * as buildInfo from './buildInfo.json'; // eslint-disable-line import/no-unresolved
 import './electron/exception';
@@ -329,6 +328,7 @@ const createWindow = () => {
   });

   if (isMac) {
+    const askFormacOSPermissions = require('./electron/macOSPermissions');
     setTimeout(() => askFormacOSPermissions(mainWindow), ms('30s'));
   }
```

Can you check whether it still works on mac?

**Comment by kris7t** [comment]
Okay, I manually pulled the `franz-catchups-mac` branch from your fork, and it seems to also work fine.

**Pull request closed without merging**
