### PR TITLE
Replace 'remote' with 'electron/remote'

### PR DESCRIPTION
**Pull request by vraravam**
### Description
Catching up with changes in electron v12+

### Motivation and Context
As we have upgraded to electron 12+, removing old/deprecated code for clean upgrade path in the future.

### Checklist:

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`$ npm run lint`)
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Comment by kris7t** [comment]
This fixes the loading error for me:

```diff
diff --git a/src/environment.js b/src/environment.js
index 5bf409a2..1aa0def0 100644
--- a/src/environment.js
+++ b/src/environment.js
@@ -12,7 +12,8 @@ import {
   PRODUCTION_TODOS_FRONTEND_URL,
 } from './config';
 
-const { app } = process.type === 'renderer' ? require('@electron/remote') : require('electron');
+// eslint-disable-next-line global-require
+export const { app } = process.type === 'renderer' ? require('@electron/remote') : require('electron');
 
 export const isDevMode = !app.isPackaged;
 export const useLiveAPI = process.env.LIVE_API;
diff --git a/src/helpers/userAgent-helpers.js b/src/helpers/userAgent-helpers.js
index df4cceb4..20509d9c 100644
--- a/src/helpers/userAgent-helpers.js
+++ b/src/helpers/userAgent-helpers.js
@@ -1,12 +1,10 @@
-import { app } from 'electron';
-import { app as remoteApp } from '@electron/remote';
 import os from 'os';
 import macosVersion from 'macos-version';
-import { isMac, isWindows } from '../environment';
+import { app, isMac, isWindows } from '../environment';
 
 // This helper gets included from the backend and frontend but we only need to use "remote"
 // if we are in the frontend
-export const ferdiVersion = remoteApp ? remoteApp.getVersion() : app.getVersion();
+export const ferdiVersion = app.getVersion();
 
 function macOS() {
   const version = macosVersion();
```

The `'remote'` module also seems to be used in a couple of recipes, btw, so maybe that's what we should try to fix next:

```sh
$ rg remote recipes
recipes/recipes/whatsapp/webview.js
4:  remote
9:const webContents = remote.getCurrentWebContents();

recipes/recipes/skype/webview.js
3:const {  remote: { BrowserWindow } } = require("electron");

recipes/recipes/googlemeet/webview.js
4:  remote
9:const webContents = remote.getCurrentWebContents();

recipes/recipes/android-messages/webview.js
4:  remote
7:const webContents = remote.getCurrentWebContents();

recipes/recipes/lastpass/webview.js
4:  remote
9:const webContents = remote.getCurrentWebContents();
```

**Comment by vraravam** [comment]
> The 'remote' module also seems to be used in a couple of recipes, btw, so maybe that's what we should try to fix next:

Yes - When I did a grep in the whole folder, it flagged the files in the `recipes` submodule folder as well. I was not sure - if we go ahead and commit both these changes, then the new recipes will no longer work with the older nightly versions of Ferdi. How should we proceed ? or do we not want to care about backwards compatibility in this case?

**Comment by vraravam** [comment]
Unfortunately, with the latest code commit - this is the latest/final error:

Screen Shot 2021-05-26 at 6 04 37 PM

(I have made the corresponding changes into the `recipes` repo and uploaded a PR for that as well)

**Comment by kris7t** [comment]
> if we go ahead and commit both these changes, then the new recipes will no longer work with the older nightly versions of Ferdi. How should we proceed ? or do we not want to care about backwards compatibility in this case?

We could come up with some loader shim thing. Like exposing a variable `useElectronRemoteModule` on the Ferdi object to recipes, and if it's not `undefined`, the recipe should `require('@electron/remote')`, else `require('electron').remote`.

> Unfortunately, with the latest code commit - this is the latest/final error:

Not sure what is happening there -- is this `npm run build` output?

**Comment by vraravam** [comment]
packaged app starts up: 
Screen Shot 2021-05-26 at 6 23 17 PM

(This also brings in - manually - the changes in the `recipes` folder.)
but, in dev mode is where I get the error from the prev screenshot.

**Comment by kris7t** [comment]
Okay, that's very strange, because it works for me in dev mode. Will try with your latest commit later today (but I have a meeting to attend in a few minutes).

**Comment by kris7t** [comment]
It's still working for me. Are you sure that `npx lerna boostrap` completed successfully?

**Review by kris7t — APPROVED** [review]
LGTM

**Pull request merged**
