### PR TITLE
Builds using GitHub actions

### PR DESCRIPTION
**Pull request by vraravam**
### Description
Since travis-ci.org is being decommissioned, we need to move to another CI tool. Since we are already on Github, we might as well switch to using GH-Actions for the same.
An added advantage of this will be that we won't need to use appveyor for windows-based builds. All building and artifacts will be "in house" per se.

### Motivation and Context
Travis-ci.org being decommissioned.

### Checklist:

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`$ npm run lint`)
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Comment by vraravam** [comment]
@kytwb - could you please do the needful to incorporate your signing keys/secrets/certs for the nightly and releases builds to pass?

**Comment by vraravam** [comment]
My test published artifacts can be found [here](https://github.com/vraravam/nightlies/releases/tag/v5.6.0-nightly.40) - please do not worry about the nightly build number - that hasn't been the focus of this PR

**Comment by vraravam** [comment]
@kytwb - once you are done with setting the secrets, please inform me - I will have to uncomment the code signing bits that are currently commented out in this PR.

**Review by kytwb — APPROVED** [review]

**Comment by kytwb** [comment]
I have added `CSC_KEY_PASSWORD`, `CSC_LINK`, `FERDI_PUBLISH_TOKEN`, `WIN_CSC_LINK`, `WIN_CSC_KEY_PASSWORD`.

**Comment by fuzzy76** [comment]
According to [this description](https://github.com/vraravam/nightlies/releases/tag/v5.6.0-nightly.57) nightlies should work once this was fixed. Is this true? Is there an issue I can follow for the nightlies?

**Comment by vraravam** [comment]
you are correct @fuzzy76 - that is the final sticky point to be unblocked. Unfortunately, @kytwb is the only one (whom I know) who has the "keys to the proverbial kingdom" (so to say). We are waiting for him to get this solved. All conversations are being conducted in the gitter channel - the link to which is in the `README.md` file.

**Pull request merged**
