### PR TITLE
Update contributions credits for mahadevans87 and sampathBlam 

### PR DESCRIPTION
**Pull request by kytwb**
Updated the release changelog already (for https://github.com/getferdi/ferdi/pull/639#issuecomment-619877707). This pull request update the CHANGELOG.md and update the contributions types from @mahadevans87 and @sampathBlam all at once as there has been a lot 😄 

Thank you guys for your contributions! 💖🙏

### CODE REVIEW

**Comment by kytwb** [comment]
Screen Shot 2020-04-30 at 11 38 16 AM

Applied from https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization#permission-levels-for-repositories-owned-by-an-organization
Let's see if it works now 🙏

**Comment by kytwb** [comment]
@vantezzen Can I get your approval please? 🙏 It seems the "Triage" role isn't enough for other contributors to review and fill pull requests requirements.

**Comment by kytwb** [comment]
@mahadevans87 @sampathBlam 🥳😄  

Screen Shot 2020-05-03 at 1 57 09 PM

Would you be ok with reaching out at hello@getferdi.com so we can arrange a call altogether with @vantezzen? 😄 We rarely call, but thought now might be a good idea! 🌟 Thank you!

**Comment by sampathBlam** [comment]
@kytwb : We shall send out an email to hello@getferdi.com by tomorrow IST (Indian Standard Time). Cheers !

**Comment by mahadevans87** [comment]
@kytwb : Like @sampathBlam said, will reach out to you tomorrow. Do you have any specific Agenda on mind that we would want to discuss so that we can prepare ourselves before the meeting?

**Comment by kytwb** [comment]
No need to prepare anything, maybe questions if you have any, otherwise it shouldn't be long either 🙂 Just taking the opportunity to welcome you and connect on another level! 🙏

**Pull request merged**
