### PR TITLE
Add "Go to Home Page" in services context menu

### PR DESCRIPTION
**Pull request by raicerk**
### Description

Add a new function to go to the home page in the added services, this function is linked with #870

### Checklist:

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`$ npm run lint`)
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Comment by kytwb** [comment]
@raicerk thank you for your contribution! 🙏 

@all-contributors please add gautamsi for code

**Comment by raicerk** [comment]
you're welcome, I just have one question!  Add gausami as a collaborator? Not me?

**Comment by raicerk** [comment]
@kytwb you're welcome, I just have one question!  Add gausami as a collaborator?  I do not?

**Comment by kytwb** [comment]
As a _contributor_, this adds you in the [thank you list](https://github.com/getferdi/ferdi#contributors-) in the README of the project.
We can still revert 05b6020 if you prefer.

**Comment by kytwb** [comment]
The bot pull request failed by the way. I will take another look at it as soon as possible.
Please clarify if you do not wish to be included in the contributors' list in the README, I don't think I clearly understood you. We also send out an invite to the GitHub organization to developers who contributed code, so feel free to accept it if you want to display the organization badge on your profile.

Thank you again for your contribution! 😄

**Comment by gautamsi** [comment]
> `@all-contributors` please add gautamsi for code

@kytwb I guess @raicerk should have been added and not me

**Comment by kytwb** [comment]
Oh, haha, that is why the bot pull request did not add anything! 😅 

Off to a slow comeback guys, bear with me! 😄 💪 

@all-contributors please add raicerk for code

**Comment by kytwb** [comment]
@all-contributors please add raicerk for code

**Comment by raicerk** [comment]
thank you @kytwb, my english is very bad, I wanted to say what he said @gautamsi 😅 thank you guys :smile:

**Pull request merged**
