### PR TITLE
Upgrade mobx-react-router from 3.x to 4.x

### PR DESCRIPTION
**Pull request by mhatvan**
### Motivation and Context

Closes https://github.com/getferdi/ferdi/issues/1569

### Checklist:

- [ ] My pull request is properly named
- [ ] The changes respect the code style of the project (`$ npm run lint`)
- [ ] I tested/previewed my changes locally

### CODE REVIEW

**Comment by mhatvan** [comment]
@vraravam I would love to hand this over to someone from the core team. The dependencies are so far behind, it is really hard to find the correct versions to make everything play along. Working efficiently is not possible due to a lot of prop type errors and deprecation warnings in the dev tools, which mask potential new errors from the dep upgrades.

The application loads fine in its current state, but navigation has to be fixed by figuring out all the breaking changes from the newer `react-router` versions. Additionally, there are some errors related to `react-jss`

**Review by vraravam — COMMENTED** [review]
Need a more comprehensive review and possibly code changes on top.

In the meantime - can we backport the compatible/non-breaking (maybe formatting + the prettier rc file) to a separate PR so that they can be merged separately in the `develop` branch?

**Comment by mhatvan** [comment]
Yeah, good point.
We would need a PR to reformat the whole project, since most files are not conforming to any code style with Prettier.

**Comment by vraravam** [comment]
> We would need a PR to reformat the whole project, since most files are not conforming to any code style with Prettier.

@mhatvan - yes, please do the same as a separate PR?

**Comment by mhatvan** [comment]
@vraravam However you prefer, I will be busy with work full-time starting tomorrow again, so might not be very fast with a new PR.

**Comment by vraravam** [comment]
> @vraravam However you prefer, I will be busy with work full-time starting tomorrow again, so might not be very fast with a new PR.

@mhatvan - I pulled only the `.prettierrc.js` file, and ran `npm run reformat-files` - but, *none of the files* were reformatted by this command. Which leads me to suspect that your IDE has reformatted (as opposed to `prettier`). Can you please try from the command-line? Or, is there some other settings file that I am missing in the new PR that I was creating?

**Comment by vraravam** [comment]
@mhatvan - please join us on gitter: https://gitter.im/getferdi/community?source=orgpage - to have more conversations

**Comment by mhatvan** [comment]
I haven't forgotten about this PR, will split it up once I find the time.

**Comment by mhatvan** [comment]
I will close this PR since its outdated, it was not related to Mobx and someone with better react-router/Mobx knowledge should take a look at it!

**Pull request closed without merging**
