### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by FerdiBot**
Enjoy!

### CODE REVIEW

**Comment by kytwb** [comment]
@all-contributors please add @Makazzz for translation

**Comment by Makazzz** [comment]
> 
> 
> @all-contributors please add @Makazzz for translation

It is just me or the bot didn't answer?

**Comment by kytwb** [comment]
It didn't answer 😅 I wasn't sure if it was slow or not. I'll add manually for now, no worries.

**Comment by kytwb** [comment]
@Makazzz Done 👍 This pull request is good to be merged? Reviewed the French translation, LGTM.

**Comment by Makazzz** [comment]
Thanks @kytwb. And for me everything seem good.

**Pull request merged**
