### PR TITLE
Add Chocolatey install instructions for Windows

### PR DESCRIPTION
**Pull request by digitalcoyote**
Add Chocolatey Install Directions

### Description
Added the markdown for Chocolatey install instructions in the style of the homebrew and AUR instructions. This should not be pulled in until the first version passes review (can take a couple weeks as the reviewers are volunteers).

### Motivation and Context
Directions for package produced in reponse to #637 

### Checklist:
- [ x] My pull request is properly named
- [x ] The changes respect the code style of the project (`$ npm run lint`)
- [x ] I tested/previewed my changes locally

### CODE REVIEW

**Comment by kytwb** [comment]
@digitalcoyote thank you for your contribution!

Please mark this pull request as ready for review once the first version is available.

**Comment by kytwb** [comment]
It is now available at https://chocolatey.org/packages/ferdi/5.5.0

**Comment by kytwb** [comment]
@all-contributors please add digitalcoyote for packaging

**Comment by kytwb** [comment]
@all-contributors please add digitalcoyote for platform

**Comment by kytwb** [comment]
@digitalcoyote I got misleaded by the number of downloads on the page.

I think it is still pending moderation, my bad.

**Comment by digitalcoyote** [comment]
I noticed that, it can be downloaded right now by specifying the version (bypasses moderation). But I believe it should be reviewed fairly soon as most of the other submissions I made in that time range have been reviewed now.

**Pull request merged**
