### PR TITLE
#87 Portable Directory working

### PR DESCRIPTION
**Pull request by Makazzz**
### Description
This is my final work on the portable env for #87 and the config folder follow !!!!

### How Has This Been Tested?
I builded Ferdi and it is working... after 2 days yay!

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist:

- [ ] My code follows the code style of this project (run `$ yarn lint`).

### CODE REVIEW

**Comment by Makazzz** [comment]
The solution was to add the code into config.js... I don't know if it isn't "clean" but it is working.

**Comment by vantezzen** [comment]
Looks like you used the same code twice (in index.js and config.js). Could you move this code into a function (I'd suggest adding a userpath helper to the helpers) and calling this function instead to avoid having duplicate code?

**Comment by Makazzz** [comment]
> 
> 
> Looks like you used the same code twice (in index.js and config.js). Could you move this code into a function (I'd suggest adding a userpath helper to the helpers) and calling this function instead to avoid having duplicate code?

The thing is I don't have enough knowledge for this. I was thinking about "import" but if you could show me an example or something, yeah I could try something

**Comment by vantezzen** [comment]
Here is the example of how password-helper is doing this:
In `src/helpers/password-helpers.js`, the function "hash" gets exported:
https://github.com/getferdi/ferdi/blob/508ab1a4a889ec4af083f307fde2bf5ba49c233e/src/helpers/password-helpers.js#L3-L5

`src/api/UserApi.js` is then importing this function:
https://github.com/getferdi/ferdi/blob/d8d5df6e72163b00e035f729b1013a957fed2321/src/api/UserApi.js#L1

And using it like a normal JavaScript function:
https://github.com/getferdi/ferdi/blob/d8d5df6e72163b00e035f729b1013a957fed2321/src/api/UserApi.js#L19

**Comment by Makazzz** [comment]
Ok so I tried something but I am getting PSoD (Purple Screen of Death) (so only purple screen and nothing is showing) with Ferdi when I am trying this instead:

index.js
```js
// Set app directory before loading user modules
export function portable() {
  if (process.env.FERDI_APPDATA_DIR != null) {
    app.setPath('appData', process.env.FERDI_APPDATA_DIR);
    app.setPath('userData', path.join(app.getPath('appData')));
  } else if (process.env.PORTABLE_EXECUTABLE_DIR != null) {
    app.setPath('appData', process.env.PORTABLE_EXECUTABLE_DIR, `${app.getName()}AppData`);
    app.setPath('userData', path.join(app.getPath('appData'), `${app.getName()}AppData`));
  } else if (process.platform === 'win32') {
    app.setPath('appData', process.env.APPDATA);
    app.setPath('userData', path.join(app.getPath('appData'), app.getName()));
  }
}

portable();
```

config.js
```js
import { portable } from './index';

portable();

export const SETTINGS_PATH = path.join(app.getPath('userData'), 'config');
```

I don't know how to correct this. Can you help me @vantezzen ?

**Comment by vantezzen** [comment]
Please move the function into a new file under the `helpers` directory and import from there.

**Comment by Makazzz** [comment]
Thanks for the info. I will do it later.

**Comment by Makazzz** [comment]
So I did it (and the export/import seem to work with helpers) but Ferdi don't want to continu after the purple screen.

**Comment by vantezzen** [comment]
Could you commit your changes so I can take a look at the code?

**Comment by vantezzen** [comment]
Hmm, the code looks good. Are there any error messages in the developer console?

**Comment by Makazzz** [comment]
I mean... Ferdi is stuck before showing anything then the purple loading screen. So I don't know how to check that.

**Comment by vantezzen** [comment]
You should still be able to choose "View" > "Show developer tools" in Ferdi's menubar

**Comment by Makazzz** [comment]
This is what I see
PSoD

**Comment by vantezzen** [comment]
Oh okay, can you revert the last commit please? I'll merge it like you had it then.

**Comment by Makazzz** [comment]
> 
> 
> Oh okay, can you revert the last commit please? I'll merge it like you had it then.

The one where I copy the code into config.js? okay

**Comment by Makazzz** [comment]
Ok I did a final build from 4b69f1d and it is working fine.

**Comment by vantezzen** [comment]
Very weird, I just tried [implementing pretty much the same code](https://github.com/getferdi/ferdi/commit/342f3bb241bd4d80838672144d9eccaec09a9239) but it seems to work fine on my computer. 
Can you try building the [improve-path-data-setup](https://github.com/getferdi/ferdi/tree/improve-path-data-setup) branch?

**Pull request merged**
