### PR TITLE
Fixing opening links in the 5.50+ versions of Ferdi

### PR DESCRIPTION
**Pull request by prasann**
### Description
Starting electron 9, support for non JS object in ipcRenderer is been removed. There was one instance in the code, that was sending a browserEvent to open the links and that was throwing an error.

https://www.electronjs.org/docs/breaking-changes#behavior-changed-sending-non-js-objects-over-ipc-now-throws-an-exception

### Motivation and Context

Fixes https://github.com/getferdi/ferdi/issues/1339

### Checklist:

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`$ npm run lint`)
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Review by vraravam — APPROVED** [review]
LGTM - this opens a new window within Ferdi (tested on the latest `develop` branch)

**Comment by vraravam** [comment]
Tested in the following services:
1) gmail - opening both within the google ecosystem and external
2) gChat - opening both within the google ecosystem and external
3) gDrive
4) github
5) gitlab
6) gitter
7) telegram react
8) gitlab

thanks @prasann !!!! 🎉

**Comment by prasann** [comment]
I still see an issue with pop-ups. links from the pop-ups aren't opening up. will check them out soon

**Comment by vraravam** [comment]
Thanks @prasann - please raise a new PR for that fix - if you are able to fix that as well!

**Comment by kris7t** [comment]
@all-contributors please add @prasann for code

**Comment by kemenaran** [comment]
@prasann thanks a lot for the fix!

**Comment by stnkl** [comment]
Nightly 55 does not fix the issue for me on Windows 10 20H2. WhatsApp and GMail both open links in a new Ferdi-popup rather than the default web browser. I didn't test any other services. Holding Ctrl while clicking a link correctly opens links in the web browser.

**Comment by amykluber** [comment]
Hi all- I'm having this issue in the Office 365 service. When I search for a document in OneDrive, I can open it from the search list, but it will not open if I click on it from the directory itself. Any fix for this?

**Comment by vraravam** [comment]
@amykluber - as long as you are on the 5.6.2 or later nightlies, you should be able to right-click and choose "open in Ferdi" from the context menu. Does that not work?

**Pull request merged**
