### PR TITLE
chore: upgrade jss and react-jss

### PR DESCRIPTION
**Pull request by mhatvan**
#### Description

Superseded by https://github.com/getferdi/ferdi/pull/2302

Cherry-pick useful code step by step out of this one and then close it.

#### Motivation and Context
Modernize codebase.

Continuation of https://github.com/getferdi/ferdi/pull/1788

#### Checklist

- [x] My pull request is properly named
- [ ] The changes respect the code style of the project (`npm run prepare-code`)
- [ ] `npm test` passes
- [ ] I tested/previewed my changes locally

### CODE REVIEW

**Comment by vraravam** [comment]
@mhatvan - this can be (at least partially solved) if we tackle #2226 first.

**Comment by vraravam** [comment]
To fix https://github.com/getferdi/ferdi/runs/3948274840?check_suite_focus=true#step:16:44 - would this be a fix?
```javascript
import * as Infobox from '../ui/Infobox';
```

**Comment by vraravam** [comment]
> To fix https://github.com/getferdi/ferdi/runs/3948274840?check_suite_focus=true#step:16:44 - would this be a fix?
> 
> ```js
> import * as Infobox from '../ui/Infobox';
> ```

This has now been committed into the `develop` branch. As soon as we can resolve the conflicts - we can try this once more

**Comment by mhatvan** [comment]
> @mhatvan - this can be (at least partially solved) if we tackle #2226 first.
> Also, it would be good to have the merge conflicts resolved so that we can try to move forward?

Yes, #2226 will help, but it is hard to tell all the code snippets that are interconnected and necessary to update to get it up and running again.
Anyhow, I fixed the merge conflicts and brought the PR up to date.

> To fix [getferdi/ferdi/runs/3948274840?check_suite_focus=true#step:16:44](https://github.com/getferdi/ferdi/runs/3948274840?check_suite_focus=true#step:16:44) - would this be a fix?
> ```js
> import * as Infobox from '../ui/Infobox';
> ```
> 
> This has now been committed into the `develop` branch. As soon as we can resolve the conflicts - we can try this once more

Thank you for fixing this. But this PR is nowhere near a mergeable state yet.

**Comment by vraravam** [comment]
All the errors (https://github.com/getferdi/ferdi/runs/4279506475?check_suite_focus=true#step:13:37) are related to #2226

**Comment by mhatvan** [comment]
We already upgraded react-jss in [#2302](https://github.com/getferdi/ferdi/pull/2302), so the rest of the code here can be copied out once we e.g convert further code to TS. I will close it for now.

**Pull request closed without merging**
