### PR TITLE
Fix proptype causing console error in nightly builds modal

### PR DESCRIPTION
**Pull request by jbellingham**
#### Description of Change
Updated proptype of actions.settings to be in line with what is being passed in.

#### Motivation and Context
Fix for [#1686](https://github.com/getferdi/ferdi/issues/1686)

#### Checklist

- [X] My pull request is properly named
- [X] The changes respect the code style of the project (`npm run prepare-code`)
- [X] `npm test` passes
- [X] I tested/previewed my changes locally

### CODE REVIEW

**Comment by jbellingham** [comment]
As a new contributor, I wasn't too sure if this was the correct solution. I found the settings actions, and it looks like it's just exported as a plain old object. Happy for any guidance from maintainers.

**Comment by vraravam** [comment]
@jbellingham - though this will fix the issue, this is not what i had in mind because it removes the type safety that we are heading towards. But, we can revisit when we convert to typescript.

**Comment by jbellingham** [comment]
Yeah I thought that might be the case. I wasn't sure exactly what the type should be.

**Comment by vraravam** [comment]
Sorry, on 2nd thoughts, I will revert this commit - please fix it in the correct manner.

**Comment by jbellingham** [comment]
I'm not entirely sure what the correct fix is here 😓  are you thinking that the settings actions being exported should be wrapped in a class in the same way the settings store is?

**Comment by vraravam** [comment]
I dont know enough of react to comment.

**Pull request merged**
