### PR TITLE
Attempt move to Vite

### PR DESCRIPTION
**Pull request by probablykasper**
#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has _stopped working_ or is _working incorrectly_, please log the bug [here](https://github.com/getferdi/recipes/issues)
2. If you are requesting support for a **new service** in Ferdi, please log it [here](https://github.com/getferdi/recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdi, but to get new recipes between Ferdi releases, this documentation is quite useful.)
4. Please consider supporting Ferdi!
  👉 https://github.com/sponsors/getferdi
  👉 https://opencollective.com/getferdi/donate
5. Please ensure you've completed all of the following.

- [ ] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [ ] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [ ] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

#### Checklist

- [ ] My pull request is properly named
- [ ] The changes respect the code style of the project (`npm run prepare-code`)
- [ ] `npm test` passes
- [ ] I tested/previewed my changes locally

### CODE REVIEW

**Comment by mhatvan** [comment]
Hey @probablykasper, amazing effort, thank you!

I was actually looking into moving Ferdi from Gulp to Vite (big fan) too a while ago and found this: https://github.com/cawa-93/vite-electron-builder, you might be able to copy some code from there or use it as a baseline.

My impression was that Vite would be too new of a technology to be used in conjunction with some old dependencies used in Ferdi (ESM vs CommonJS). There is also: https://github.com/electron/electron/issues/21457

That's why I started https://github.com/getferdi/ferdi/pull/1783 instead, but I would love to rather use Vite, let's see if there's a way to make it work. In case you get stuck, I would be happy to help out.

**Comment by probablykasper** [comment]
@mhatvan I kinda did get stuck on this, but wanted to put out the progress I made. Main reason for doing this is that I wanted get tree shaking (https://github.com/getferdi/ferdi/issues/2347).

Not 100% sure if Vite will work for Ferdi, but fingers crossed. I'm guessing vite-electron-builder did manage to compile for CommonJS, at least.

This is what I've gotten around so far:
- JS files contain JSX. Renamed those files to `.jsx`
- Support for decorators like `@observable`. Added babel plugin `@babel/plugin-proposal-decorators`. Also added `@babel/plugin-proposal-class-properties`, which might not be necessary.
- `buildInfo.json`. Made a plugin that emits the `buildInfo.json` file + added `buildInfo` variable to Vite `define` option, which makes it available as a global variable.
- SCSS support. Turned the variables into a string of SCSS statements, which are passed to the `additionalData` option.

**Comment by probablykasper** [comment]
ToDo:
- [ ] `app.jsx` output is basically empty for some reason
- [ ] Deal with the inline `<script>` in `index.html`
- [ ] Error from `cld` dependency:

    <details>
    <summary>Error</summary>
    
    ```
    Could not resolve './build/Release/cld' from ./build/Release/cld?commonjs-external
    error during build:
    Error: Could not resolve './build/Release/cld' from ./build/Release/cld?commonjs-external
        at error (/Users/k/dev/git/ferdi/node_modules/rollup/dist/shared/rollup.js:158:30)
        at ModuleLoader.handleResolveId (/Users/k/dev/git/ferdi/node_modules/rollup/dist/shared/rollup.js:22320:24)
        at /Users/k/dev/git/ferdi/node_modules/rollup/dist/shared/rollup.js:22299:26
    ```
    
    </details>

- [ ] Error due to `@adonisjs/ignitor` assigning to `process.env`:

    <details>
    <summary>Error</summary>
    
    ```
    [commonjs] Assigning to rvalue (835:6) in /Users/k/dev/git/ferdi/node_modules/@adonisjs/ignitor/src/Ignitor/index.js
    file: /Users/k/dev/git/ferdi/node_modules/@adonisjs/ignitor/src/Ignitor/index.js:835:6
    833:      */
    834:     if (process.argv.slice(2)[0] === 'test') {
    835:       process.env.NODE_ENV = 'testing'
               ^
    836:     }
    error during build:
    SyntaxError: Assigning to rvalue (835:6) in /Users/k/dev/git/ferdi/node_modules/@adonisjs/ignitor/src/Ignitor/index.js
        at Parser.pp$4.raise (/Users/k/dev/git/ferdi/node_modules/rollup/dist/shared/rollup.js:19537:13)
        at Parser.pp$7.toAssignable (/Users/k/dev/git/ferdi/node_modules/rollup/dist/shared/rollup.js:18030:12)
        at Parser.pp$5.parseMaybeAssign (/Users/k/dev/git/ferdi/node_modules/rollup/dist/shared/rollup.js:18553:21)
        at Parser.pp$5.parseExpression (/Users/k/dev/git/ferdi/node_modules/rollup/dist/shared/rollup.js:18510:19)
        at Parser.pp$8.parseStatement (/Users/k/dev/git/ferdi/node_modules/rollup/dist/shared/rollup.js:17042:45)
        at Parser.pp$8.parseBlock (/Users/k/dev/git/ferdi/node_modules/rollup/dist/shared/rollup.js:17328:21)
        at Parser.pp$8.parseStatement (/Users/k/dev/git/ferdi/node_modules/rollup/dist/shared/rollup.js:17010:36)
        at Parser.pp$8.parseIfStatement (/Users/k/dev/git/ferdi/node_modules/rollup/dist/shared/rollup.js:17157:26)
        at Parser.pp$8.parseStatement (/Users/k/dev/git/ferdi/node_modules/rollup/dist/shared/rollup.js:16999:33)
        at Parser.pp$8.parseBlock (/Users/k/dev/git/ferdi/node_modules/rollup/dist/shared/rollup.js:17328:21)
    ```
    
    </details>

- [x] `'arch' is not exported by __vite-browser-external, imported by src/environment.ts`. Fixed by adding `...builtinModules` to `build.rollupOptions.external`.
- [ ] Make sure external dependencies are bundled
- [ ] Deal with optionalDependencies. Might just need to specify `node-mac-permissions` as external.

**Comment by probablykasper** [comment]
Not quite sure how to get around this one:
```
(this will be run only when your dependencies or config have changed)
 > node_modules/electron-fetch/lib/index.es.js:3:9: error: No matching export in "browser-external:http" for import "STATUS_CODES"
    3 │ import { STATUS_CODES } from 'http';
      ╵          ~~~~~~~~~~~~

 > node_modules/electron-fetch/lib/index.es.js:6:17: error: No matching export in "browser-external:stream" for import "PassThrough"
    6 │ import Stream, { PassThrough } from 'stream';
      ╵                  ~~~~~~~~~~~

 > node_modules/react-virtualized/dist/es/WindowScroller/utils/onScroll.js:74:9: error: No matching export in "node_modules/react-virtualized/dist/es/WindowScroller/WindowScroller.js" for import "bpfrpt_proptype_WindowScroller"
    74 │ import { bpfrpt_proptype_WindowScroller } from "../WindowScroller.js";
       ╵          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error when starting dev server:
Error: Build failed with 3 errors:
node_modules/electron-fetch/lib/index.es.js:3:9: error: No matching export in "browser-external:http" for import "STATUS_CODES"
node_modules/electron-fetch/lib/index.es.js:6:17: error: No matching export in "browser-external:stream" for import "PassThrough"
node_modules/react-virtualized/dist/es/WindowScroller/utils/onScroll.js:74:9: error: No matching export in "node_modules/react-virtualized/dist/es/WindowScroller/WindowScroller.js" for import "bpfrpt_proptype_WindowScroller"
    at failureErrorWithLog (/Users/k/dev/git/ferdi/node_modules/vite/node_modules/esbuild/lib/main.js:1493:15)
    at /Users/k/dev/git/ferdi/node_modules/vite/node_modules/esbuild/lib/main.js:1151:28
    at runOnEndCallbacks (/Users/k/dev/git/ferdi/node_modules/vite/node_modules/esbuild/lib/main.js:941:63)
    at buildResponseToResult (/Users/k/dev/git/ferdi/node_modules/vite/node_modules/esbuild/lib/main.js:1149:7)
    at /Users/k/dev/git/ferdi/node_modules/vite/node_modules/esbuild/lib/main.js:1258:14
    at /Users/k/dev/git/ferdi/node_modules/vite/node_modules/esbuild/lib/main.js:629:9
    at handleIncomingPacket (/Users/k/dev/git/ferdi/node_modules/vite/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/Users/k/dev/git/ferdi/node_modules/vite/node_modules/esbuild/lib/main.js:596:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
```

**Pull request closed without merging**
