### PR TITLE
Franz catchups

### PR DESCRIPTION
**Pull request by vraravam**
### Description
Some commits brought over from franz repo related to fixing of crashes, big sur changes, etc

### Motivation and Context
Catchup to Franz 5.6.0 (but some of the changes do not work - so, haven't copied them over).

### Checklist:

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`$ npm run lint`)
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Comment by vraravam** [comment]
@kris7t - were you able to try this branch out in your linux box?

**Comment by kris7t** [comment]
1. Browser control icons in dark mode: seems to be fixed now. ☺️
2. Tray icon color in Big Sur: can't comment, no mac.
3. Crashes on navigations changes/reloads:  #1029 is still broken 😞
4. Entitlements for screen-capture-permissions: no mac for me.
5. Upgraded `electron-builder`: seems to have no ill effects. ☺️
6. Add missing dependencies on Linux: I still think creating an `rpm` package at all times is a bad idea (not all distros are `rpm`-based), but at least now we have documented this. 😐
7. Remove unused entitlements file: no mac for me.

**Comment by vraravam** [comment]
btw, @kris7t / @kytwb - I haven't updated the `README.md` with any of the above. I would assume that this will be done as part of getting ready for the 5.6.0 release?

**Comment by kris7t** [comment]
Looks like we have to disable COOP something like this:

```diff
diff --git a/src/index.js b/src/index.js
index b29cec83..3ce93660 100644
--- a/src/index.js
+++ b/src/index.js
@@ -378,7 +378,10 @@ if (argv['auth-negotiate-delegate-whitelist']) {
 }
 
 // Disable Chromium's poor MPRIS implementation
-app.commandLine.appendSwitch('disable-features', 'HardwareMediaKeyHandling,MediaSessionService');
+// and apply workaround for https://github.com/electron/electron/pull/26432
+app.commandLine.appendSwitch('disable-features', 'HardwareMediaKeyHandling,MediaSessionService,CrossOriginOpenerPolicy');
+
+app.allowRendererProcessReuse = false;
 
 // This method will be called when Electron has finished
 // initialization and is ready to create browser windows.
```

We already have some `disable-features`, so we have to append to that list instead of pushing a whole new command line argument.

**Comment by vraravam** [comment]
Thanks @kris7t - I'm in the process of separating out the mac-specific
changes away from that PR. That way, you can review and merge the ones that
are ok for you on linux. Please give me a few mins

**Comment by vraravam** [comment]
To be merged AFTER #1372 is merged (so that testing of macos-related changes can be done here in this PR)

**Pull request merged**
