### PR TITLE
[Branding] Changed occurrences of 'Franz' to 'Ferdi'

### PR DESCRIPTION
**Pull request by vraravam**
### Description
Lots of occurrences (especially debug tags) were still referring to 'Franz' - changed these to 'Ferdi'

### Motivation and Context
Rebanding

### Checklist:

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`$ npm run lint`)
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Comment by dpeukert** [comment]
@vraravam Just a heads-up, this commit caused my install to spit out `Could not load services and user information` (no relevant errors in the console or in stdout as far as I can tell) and to not load my config. I haven't had the time to dig further.

**Comment by vraravam** [comment]
@dpeukert - I am running the commit in my local (macos) without any issues. Looking at the code where the error `Could not load services` is present, it might be related to some network issues. Please try again. Tx for merging the PR

**Comment by dpeukert** [comment]
@vraravam Strange, I'm running on Linux and was able to reproduce this on two different machines on two different networks. Downgrading to the previous commit also worked with no network changes. I'm not using the online account though, so that might be a factor.

**Comment by vraravam** [comment]
@dpeukert - we reverted a part of this PR related to headers. This might have caused your issue as well. Could you please re-verify?

**Comment by dpeukert** [comment]
@vraravam Thanks for the heads-up, d3f5184 indeed fixed the problem.

**Pull request merged**
