### PR TITLE
Quick switch enhancements

### PR DESCRIPTION
**Pull request by vraravam**
### Description
1) Quick Switcher now supports regex
2) Fix issue with incorrect handling of Shift+Tab in quick switcher.

### Motivation and Context
Fixing some papercuts while using Quick Switcher

### Screenshots
Default (no search term): 
Screen Shot 2021-05-01 at 8 30 19 AM
Matches without any regex: 
Screen Shot 2021-05-01 at 8 30 38 AM
Matches with javascript regex:
Screen Shot 2021-05-01 at 8 41 05 AM

### Checklist:

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`$ npm run lint`)
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Comment by vraravam** [comment]
@kris7t @kytwb - can anyone please validate and merge?

**Comment by kris7t** [comment]
Seems to be working fine. But I have two questions:

1. Is this really what we want for #1311? Fuzzy search usually refers to something else, like in [fzf](https://github.com/junegunn/fzf). Would that be feasible to do instead? (Typed characters should appear in the service name in order, but may have any characters interspersed. I think there's some ordering to prefer continuous runs of characters. Matched characters are highlighted to show the match.)
2. When I press `Ctrl+S` to trigger the quick switcher, the search box is not focused. This might be an Electron limitation (focus stays inside the webview). Is it possible to fix?

**Comment by vraravam** [comment]
1. The description by the OP - he is asking for a contains search (not a fuzzy search). But, are you referring to some fuzzy-search-based npm module? I can give that a try (but, I'm not a javascript developer - so, it might take some time - and with the week starting, not sure how much time I have)
2. Yes, I had logged the issue that you linked. Not sure if this is possible atm.

**Comment by kytwb** [comment]
LGTM, thanks!

**Pull request merged**
