### PR TITLE
Conditionally display Menu items based on lock state

### PR DESCRIPTION
**Pull request by kytwb**
### Description

Fixes https://github.com/getferdi/ferdi/issues/404 by leaving useful/non-sensitive items in the menu when locked (instead of no menu items at all previously, which led to the shortcuts being broken). Coupled with https://github.com/getferdi/ferdi/pull/393, it should also help solve #362 (and #377, cc @aleksabobic).

### Screenshots (if appropriate):

Kapture 2020-02-27 at 3 17 35

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code follows the code style of this project (run `$ yarn lint`).

### CODE REVIEW

**Comment by kytwb** [comment]
Noted for the menu debug entries. Otherwise, I am for shipping this fix (once I address the previous note) before further refactoring if you're ok with it. I think I will treat the way we store the password and touch ID support at the same time.

**Comment by kytwb** [comment]
@vantezzen Anything else before I can merge this one?  
Addressed the debug menu items via ef2dae8.

**Comment by vantezzen** [comment]
No, looks good

**Comment by kytwb** [comment]
Cool! Could you approve the pull request then please?  
I guess you just forgot, just wanted to make sure.
Thank you!

**Pull request merged**
