### PR TITLE
Upgraded electron to '12.0.5'.

### PR DESCRIPTION
**Pull request by vraravam**
### Description
Upgraded electron to 12.0.5. This might need a bit more of testing from other contributors and on different OS combinations.
**CAVEAT:** Though Ferdi runs fine after starting, the window doesn't appear on macOs till I move focus away from Ferdi into another app, and then refocus (Cmd+Tab) onto Ferdi.

### Motivation and Context
Trying to stay on the latest released version of electron for speed and security benefits.

### Checklist:

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`$ npm run lint`)
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Comment by kytwb** [comment]
@vraravam thanks!

**Comment by vraravam** [comment]
@kytwb - thanks for merging - but, i was hoping for someone to validate the caveat that I had listed in the above description. @arioki1 - would you be willing to try this out in your machine please?

**Comment by kris7t** [comment]
@vraravam First of all, thanks for keeping Ferdi up to date! :)

I'm trying to run Ferdi with Electron 12.0.5 and nodejs 12.22.0 on Arch Linux. However, my attempts at both running from the source tree (with `npm run dev`/`npm run start`) as well as from an installable package using system Electron fail.

In the devloper console, I have the errors

```
VM75 renderer_init.js:13 (electron) The remote module is deprecated. Use https://github.com/electron/remote instead.
log @ VM75 renderer_init.js:13
VM75 renderer_init.js:93 Unable to load preload script: /home/kris/urandom/ferdi/build/sentry.js
(anonymous) @ VM75 renderer_init.js:93
VM75 renderer_init.js:93 TypeError: electron_1.crashReporter.start is not a function
    at RendererBackend._installNativeHandler (backend.ts:102)
    at new RendererBackend (backend.ts:21)
    at new BaseClient (baseclient.ts:67)
    at new RendererClient (client.ts:22)
    at Object.initAndBind (sdk.ts:19)
    at Object.init (index.ts:18)
    at Object.specificInit (dispatch.ts:122)
    at Object.init (sdk.ts:57)
    at Object.<anonymous> (VM76 sentry.js:9)
    at Object.<anonymous> (VM76 sentry.js:12)
(anonymous) @ VM75 renderer_init.js:93
app.js:3 Uncaught ReferenceError: require is not defined
    at app.js:3
index.html:15 Uncaught ReferenceError: process is not defined
    at index.html:15
VM75 renderer_init.js:113 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
(anonymous) @ VM75 renderer_init.js:113
```

Closest I could find is https://github.com/nodejs/node/issues/33741 , so it seems Electron is trying to treat `src/app.js` as a JSM module? The issue https://github.com/laurent22/joplin/issues/4859 also seems related and also involves Arch.

On the other hand, building from f71e17f3f6b5ca63bdce7d08a70cc35a6109e2fa works fine, so this seems to be an issue related to Electron 12 only.

**Comment by vraravam** [comment]
thanks @kris7t - I will initiate a PR to revert this one. As I mentioned in the caveatt up in the description field - there is at least 1 other known issue with this upgrade on MacOS.

**Pull request merged**
