### PR TITLE
Improve information about Premium subscriptions and Teams

### PR DESCRIPTION
**Pull request by vantezzen**
As seen in #496, the current way Ferdi displays information about the Premium status may be irritating to new users.
This commit will:
- Hide all premium sections if we are not using the Franz server as they are not used with Ferdi servers
- Hide teams section if we are not using the Franz server as Ferdi servers do not support Teams
- Update the description on the Teams page to indicate that Teams are of no use in Ferdi
- Fix accessing the Team Management page to redirect to meetfranz.com instead of getferdi.com
- Hide the "Delete Account" section on the accounts page as accounts on Ferdi servers can be deleted through the Dashboard and not though Ferdi

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist:

- [x] My code follows the code style of this project (run `$ yarn lint`).

### CODE REVIEW

**Comment by kytwb** [comment]
With Franz server:

Screen Shot 2020-03-25 at 6 47 14 PM


Screen Shot 2020-03-25 at 6 47 07 PM

With Ferdi server:

Screen Shot 2020-03-25 at 6 45 17 PM

**Comment by vantezzen** [comment]
Screenshot 2020-03-28 at 09 36 01

I cannot reproduce your problem with the titles having the wrong the right text color - are you still seeing that problem?

**Comment by kytwb** [comment]
This is an issue related to Dark Mode, will address in another pull request.

**Comment by aminebenj** [comment]
Hi,
Why this important feature is disabled ?
Can we easily add it if we use our own server ?
Thank you

**Comment by vantezzen** [comment]
@aminebenj This PR doesn't disable any features: The "Teams" and "Premium" sections are only useful when using Franz's server as Ferdi's servers don't offer such a functionality - when you are using Ferdi's servers all premium features are already available.
This is why we hide those sections to make it more clear that they are not needed.

**Comment by aminebenj** [comment]
@vantezzen So maybe I m posting in the wrong PR. But I wanted to understund is why we can't have Teams on Ferdi's servers? Is it a choice? Because I think that it a very interesting feature.
If I have some answers or guidelines maybe i can help doing it and then make a pull request to add it.

We can at least keep it when people use their own server.

**Comment by kytwb** [comment]
@aminebenj there is another issue referenced in this pull request that seem to answer your question:

Screen Shot 2020-04-02 at 9 25 21 AM

See https://github.com/getferdi/ferdi/issues/496#issuecomment-603861664:

> Ferdi doesn't officially support Franz Teams and there is no support for Teams on custom Ferdi servers.
The reason for this is that Ferdi doesn't offer any "premium" subscriptions, thus making Franz's Team management useless as that is only used to manage subscriptions for multiple users.
We may remove the "Teams" page in the future to make this more clear.

**Comment by aminebenj** [comment]
@kytwb Thank you for your clarification.

At First, I thought that teams are made to collaborate in the same tools. and give coworkers access to the same accounts in tools like shared email boxes...

Can Ferdi be usefull for this usecase ?

**Comment by kytwb** [comment]
@aminebenj Thank you for sharing your use case.  
At the moment, Ferdi server is used to sync services. That means if you use Ferdi with an account on computer A, then login on computer B with the same account on the same server, you won't have to reconfigure Ferdi. For security reasons, we can't share active sessions, so you would have to re-login to each services on computer B.

**Comment by kytwb** [comment]
@aminebenj To answer your question, Ferdi isn't optimized for your use case (as any way your coworker would have to re-login, as in _you can't give coworkers access to the same accounts_ thanks to Ferdi). An interesting part of your use case we could maybe take a look at is improving the use of shared account (as in you can use 1 account for you and your workers so you all have the same services in Ferdi and are all in the same page when it comes to what services are used at work), or offer a "import services" feature where you could share you current services to your coworkers, and each to their accounts would import the list of services you shared. WDYT? /cc @vantezzen

**Comment by vantezzen** [comment]
You already offer such (or a similar) functionality: You can create your services in Ferdi and export your configuration over Ferdi's dashboard (at api.getferdi.com) and let your coworkers import that configuration so they have the same services.

**Comment by aminebenj** [comment]
@kytwb It can be interesting. Sharing the same account, feels like a hack (as we will use the same password) and has the same security issues level as having a team in the back side. So in that case better doing the teams.
Importing services avoid Ferdi to manage all security issues so it can be a good idea. But i give the user more security issues to manage. Be sure that no one export the companies services...

**Comment by vantezzen** [comment]
> You already offer such (or a similar) functionality: You can create your services in Ferdi and export your configuration over Ferdi's dashboard (at api.getferdi.com) and let your coworkers import that configuration so they have the same services.

Also, you can theoretically give coworkers access to the same account - as sessions aren't shared over the server, you can all use the same configuration with different accounts.

**Pull request merged**
