### PR TITLE
Give credit to all contributors

### PR DESCRIPTION
**Pull request by kytwb**
For https://github.com/getferdi/ferdi/issues/236. Working on the display first, then adding whoever is missing.

### CODE REVIEW

**Comment by kytwb** [comment]
Re-synced with develop, current status:

Screen Shot 2020-02-29 at 5 17 00 AM

Depends on https://github.com/all-contributors/all-contributors/issues/85#issuecomment-567561230.  
I forked the CLI and will play around with it to try and remove the table and make the contributions list available in a way that it can be reflected in the image title on mouseover.

**Comment by kytwb** [comment]
@vantezzen what do you think about merging the current status of things so I can start adding all the contributors that came up with great feedback, got involved in investigating open issues etc? We would still have the data regarding the contributions (emojis), but it would not be displayed temporarily until we contribute back to all-contributors/all-contributors#85.

**Comment by vantezzen** [comment]
Screenshot 2020-04-17 at 20 25 00

I currently have the problem that this is what the contributors look like on smaller/slimmer screens. Also, I'd suggest changing the "alt" text to display the type of contributions (something like "<name> contributed code, design, bug" using the emoji keys we already have), but I don't know if that is possible

**Comment by kytwb** [comment]
Current status with a quick local hack to all-contributors-cli:

Screen Shot 2020-04-21 at 11 55 28 PM

**Comment by kytwb** [comment]
I was thinking of using a fork with the local hack as dependency for all-contributors-cli, but that wouldn't work as we most often use the GitHub bot, which would generate the contributors list using the official version. We will have to contribute to all-contributors-cli if we want the minimal version 😛

**Comment by vraravam** [comment]
@kytwb @vantezzen - any idea when this PR might be completed?

**Comment by vraravam** [comment]
Closing this PR since I cherry-picked the commits, squashed them, implemented @vantezzen 's template changes, and merged into `develop` branch.

**Pull request closed without merging**
