### PR TITLE
Fix Issue #1109: Expose relevant info about Electron, node, platform,…

### LINKED ISSUE #1109: Expose Electron version information in "About Ferdi"
**Is your feature request related to a problem? Please describe.**
Not really a problem, but imo, exposing the Electron version in the "about" dialog will enable others to know if/when there's a security-related issue discovered in an older version of electron.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by vraravam**
… architecture in the 'About' dialog.

### Description
Fixes #1109 and included more info as was previously already present for Windows version of Ferdi.

### Motivation and Context
As techies/developers who contribute to Ferdi, we need a quick way to access the pertinent information.
Also, for security-aware non-techies, exposing the Electron version in the 'About' dialog will reassure them of us being ahead of the curve in adopting newer Electron releases for security patches.

### Screenshots
Screen Shot 2021-04-28 at 11 55 34 AM

### Checklist:

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`$ npm run lint`)
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Comment by kris7t** [comment]
I've tried merging this locally on top of #1308, and my about box is the same as it were before. This is a bit suprising, as I would have expected it to display `Arch: x64` as a new piece of info. Nevertheless, not both platforms display roughly the same info.

It seems about dialog behavior is not consistent across platforms in Electron, though: https://github.com/electron/electron/issues/23851

**Comment by vraravam** [comment]
Yes, each os seems to be different.

sent using an itty-bitty keyboard that assumes it can think

**Comment by vraravam** [comment]
@kytwb @vantezzen - please merge asap?

**Comment by kytwb** [comment]
@vraravam thanks!

**Pull request merged**
