### PR TITLE
Synchronize with Franz 5.6.0

### PR DESCRIPTION
**Pull request by kytwb**
### Description

This pull request aim at syncing with the upstream (Franz) latest release, v5.6.0-beta.1 ([changelog](https://github.com/meetfranz/franz/releases/tag/v5.6.0-beta.1)).

### Motivation and Context

For https://github.com/getferdi/ferdi/issues/1017.

### Checklist:

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`$ npm run lint`)
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Comment by kytwb** [comment]
I was facing the following issue:

```
kytwb@kytwbs-MacBook-Pro ferdi % npx lerna run prepare
lerna notice cli v3.19.0
lerna info versioning independent
lerna info Executing command in 3 packages: "npm run prepare"
lerna ERR! npm run prepare exited 2 in '@meetfranz/theme'
lerna ERR! npm run prepare stdout:

> @meetfranz/theme@1.0.14 prepare /Users/kytwb/Projects/Ferdi/ferdi/packages/theme
> tsc

../../node_modules/@types/react-jss/index.d.ts(9,57): error TS7016: Could not find a declaration file for module 'theming'. '/Users/kytwb/Projects/Ferdi/ferdi/node_modules/theming/dist/cjs/index.js' implicitly has an 'any' type.
  Try `npm install @types/theming` if it exists or add a new declaration (.d.ts) file containing `declare module 'theming';`
../../node_modules/@types/react-jss/lib/injectSheet.d.ts(10,8): error TS7016: Could not find a declaration file for module 'theming'. '/Users/kytwb/Projects/Ferdi/ferdi/node_modules/theming/dist/cjs/index.js' implicitly has an 'any' type.
  Try `npm install @types/theming` if it exists or add a new declaration (.d.ts) file containing `declare module 'theming';`

lerna ERR! npm run prepare stderr:
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @meetfranz/theme@1.0.14 prepare: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @meetfranz/theme@1.0.14 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kytwb/.npm/_logs/2020-10-18T10_13_54_675Z-debug.log

lerna ERR! npm run prepare exited 2 in '@meetfranz/theme'
```

This was due to removing the lockfile in hope to regenerate it with `npx lerna bootstrap`.
Instead, I fixed the conflicts in `package.json` and re-ran `npx lerna bootstrap`, which auto-resolved the conflicts in the lockfile and successfully bootstrapped the project again:

```
kytwb@kytwbs-MacBook-Pro ferdi % npx lerna bootstrap
lerna notice cli v3.19.0
lerna info versioning independent
lerna info bootstrap root only
npm WARN conflict A git conflict was detected in package-lock.json. Attempting to auto-resolve.
npm WARN conflict To make this happen automatically on git rebase/merge, consider using the npm-merge-driver:
npm WARN conflict $ npx npm-merge-driver install -g
...
lerna success run Ran npm script 'prepare' in 3 packages in 18.1s:
lerna success - @meetfranz/forms
lerna success - @meetfranz/theme
lerna success - @meetfranz/ui

added 720 packages from 218 contributors, removed 529 packages, updated 438 packages and moved 49 packages in 145.106s

50 packages are looking for funding
  run `npm fund` for details

```

**Comment by kytwb** [comment]
Personal checklist:

- [ ] Not sure why we added "node-abi": "2.19.1" in package.json
- [ ] Not sure why we switched from "cld3-asm" to "cld "
- [ ] Languages don’t all have translations in between parenthesis in language.js
- [ ]   Make hibernation work with preferred hibernation timeout set in settings
- [ ] Review context menu to add missing Franz entries (save image, go back, go forward, ...)
- [ ] Review translations, I think I have lost some in the merge

I went with re-using Franz implementation for hibernation and spellchecking as to avoid double maintenance in the future.

To be continued.

**Comment by kytwb** [comment]
Getting back to this soonish.

**Comment by proletarius101** [comment]
Are you still working on it?

**Comment by kytwb** [comment]
@proletarius101 yes.

**Comment by kytwb** [comment]
I'm merging this to make it available to `develop` and following up in #1017

**Pull request merged**
