### PR TITLE
Improve README.md

### PR DESCRIPTION
**Pull request by Makazzz**
# Description
This is an upgraded version of the README.md I made. Tell me if something is wrong with it.
See the change [here](https://github.com/Makazzz/ferdi/blob/readme/README.md)

### Motivation and Context
I did this because I wanted to add screenshots, table of contents, update shield.io badge, add description etc.

### CODE REVIEW

**Comment by kytwb** [comment]
When creating a pull request, you have the option to create a draft instead of putting a [TAG] in the pull request title:

Screen Shot 2019-10-26 at 1 26 38 PM

**Comment by vantezzen** [comment]
I would suggest changing the "What is Ferdi" text to something like:

> Ferdi is a messaging browser that allows you to combine your favorite messaging services into one application. 
> It is based on Franz - a software already used by thousands of people - with the difference that Ferdi gives you many additonal features and doesn't restrict its usage!
> Ferdi is compatible with your existing Franz account so you can continue right where you left off.
> Find out more about Ferdi and its features on [getferdi.com](https://getferdi.com/)

**Comment by Makazzz** [comment]
> 
> 
> I would suggest changing the "What is Ferdi" text to something like:
> 
> > Ferdi is a messaging browser that allows you to combine your favorite messaging services into one application.
> > It is based on Franz - a software already used by thousands of people - with the difference that Ferdi gives you many additonal features and doesn't restrict its usage!
> > Ferdi is compatible with your existing Franz account so you can continue right where you left off.
> > Find out more about Ferdi and its features on [getferdi.com](https://getferdi.com/)

Thanks, I will do that.

**Comment by vantezzen** [comment]
Can we merge?

**Pull request merged**
