### PR TITLE
Upgrade 'electron' to '16.0.5' and '@electron/remote' to '2.0.1'

### PR DESCRIPTION
**Pull request by vraravam**
#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has _stopped working_ or is _working incorrectly_, please log the bug [here](https://github.com/getferdi/recipes/issues)
2. If you are requesting support for a **new service** in Ferdi, please log it [here](https://github.com/getferdi/recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdi, but to get new recipes between Ferdi releases, this documentation is quite useful.)
4. Please consider supporting Ferdi!
  👉 https://github.com/sponsors/getferdi
  👉 https://opencollective.com/getferdi/donate
5. Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change
Upgraded `electron` and `electron/remote` packages.

_Note_: The file-chooser dialog and the context menus are broken. The related issues that I have logged are: https://github.com/electron/electron/issues/31854 and https://github.com/electron/electron/issues/31855 - Please do not merge till they are fixed.

Looks like the unread counter/badge is also broken - I haven't logged a ticket for it though

#### Motivation and Context
Keeping up-to-date with new electron versions for features and security fixes.

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`npm run prepare-code`)
- [x] `npm test` passes
- [ ] I tested/previewed my changes locally

### CODE REVIEW

**Comment by vraravam** [comment]
Also (maybe) related: https://github.com/MarshallOfSound/react-electron-web-view/issues/35

**Comment by vraravam** [comment]
@kris7t - could you help with this? Looks like https://github.com/vraravam/ferdi/blob/develop/src/components/services/content/ServiceWebview.js#L82 needs to also be wrapped within an `enableRemote()` call.

**Comment by vraravam** [comment]
The crash of the file-chooser dialog has been fixed by https://github.com/electron/electron/issues/31854

**Comment by mhatvan** [comment]
Great! Any other issues left that hinders the merge?

**Comment by vraravam** [comment]
> @kris7t - could you help with this? Looks like https://github.com/vraravam/ferdi/blob/develop/src/components/services/content/ServiceWebview.js#L82 needs to also be wrapped within an `enableRemote()` call. This might be the only fix for the other issues as well (just a hunch)

@mhatvan - this is the next blocker. I feel this might solve both the outstanding issues of the context menu and the unread badges

**Comment by vraravam** [comment]
Any updates on this? The context menu and the unread badge counter are still the blockers for this.

**Comment by kris7t** [comment]
Sorry for not getting back to this earlier -- I managed to check out this branch and run it with `npm` 8, now I'm trying to look at the `enableRemote` calls.

A complication is that I can't seem to open the service developer tools. I guess the issue also prevent Ferdi communicating with the recipe webview to open the devtools window...

**Comment by vraravam** [comment]
Thanks for the explanation @kris7t - the right-click contextMenu is also still broken

**Comment by kris7t** [comment]
That's strange, the context menu seems to work for me after the workaround. Maybe it's mac specific?

**Comment by kris7t** [comment]
Upgrading to electron 16.0.2 fixes the issue with screen sharing for me.

**Comment by vraravam** [comment]
@kytwb - if you have time, please help with this PR. I have rebased from the latest `develop` as of an hour ago now - but, the context menu is still broken for me on macos.

**Comment by vraravam** [comment]
UPDATE: This is now working after rebasing from `develop` and upgrading `electron` to `16.0.5` 🎉

Can we get some more testing on linux and windows before merging?

**Comment by vraravam** [comment]
Closing since i am not contributing to software headed by autocracy

**Pull request closed without merging**
