### PR TITLE
Change Release for Electron and replace leftover Franz reference

### PR DESCRIPTION
**Pull request by Makazzz**
### Description
Simply replace "Release" with Electron for more clarity.
AND
replace leftover of franz link in the ? menu
### Motivation and Context

Its not about a problem but more about for a clarity. Because if a new user go in the About Ferdi and see this
```
Version: 5.3.4-beta.4
Release: 6.0.10 / win32 / x64
```
it will be confusing about and be like "Why is there two version about Ferdi?"

AND

The leftover about Franz is still in Ferdi. And [it was discussed 9 days ago](https://github.com/getferdi/ferdi/issues/59) but the build are still not changing the branding.

> "Learn more" links to https://meetfranz.com/ and not https://getferdi.com,
"Changelog" links to https://github.com/meetfranz/franz/blob/master/CHANGELOG.md and not https://github.com/getferdi/ferdi/blob/master/CHANGELOG.md,
"Support" links to https://meetfranz.com/support and not https://getferdi.com/contact,
"Terms of service" links to https://meetfranz.com/terms and not https://getferdi.com/terms,
"Privacy Statement" links to https://meetfranz.com/privacy and not https://getferdi.com/privacy.
### How Has This Been Tested?

I did the test from the Appveyor build and it is working.

### Screenshots (if appropriate):
changereleaseforelectron

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist:

- [ ] My code follows the code style of this project (run `$ yarn lint`).

### CODE REVIEW

**Comment by vantezzen** [comment]
See [#80 (comment)](https://github.com/getferdi/ferdi/issues/80#issuecomment-536259090)

**Comment by vantezzen** [comment]
@all-contributors Please add @Makazzz for bug, code

**Comment by Makazzz** [comment]
Thanks a lot for your reply @vantezzen. I made the change and I will test the appveyor build when ready.

**Comment by vantezzen** [comment]
I fixed the remaining errors in the termsBase generation with 4fde59b and merged your changed into master.

Thank you for your contribution.

**Comment by Makazzz** [comment]
Thanks you so much for this I was going nowhere with this fix.

**Pull request merged**
