### PR TITLE
#270 Add more navigation bar behaviour settings

### PR DESCRIPTION
**Pull request by vantezzen**
This PR will switch from having the single "Show Navigation Bar in all services" to a three-option select:
Screenshot 2020-02-23 at 21 57 59
Screenshot 2020-02-23 at 21 58 06

As requested in #270.

The default selected option is "Show navigation bar on custom websites only"

### CODE REVIEW

**Comment by kytwb** [comment]
Should we make the setting backward compatible by initializing/overriding the default value of `navigationBarBehaviour` by the appropriate user settings value based on the old `showServiceNavigationBar` if it exists?

**Comment by vantezzen** [comment]
We can integrate that into the settings migrator:

https://github.com/getferdi/ferdi/blob/87dd31f8e636c9f7f6b89955f6d9d298d6273e14/src/stores/SettingsStore.js#L192

**Comment by vantezzen** [comment]
Add migration via c74a0481

**Comment by vraravam** [comment]
Can we get this PR merged and a new beta released? I would love to try this out!

**Comment by kytwb** [comment]
@vraravam We will make a release in the coming days as soon as we've merged all the open pull requests and did a review to make sure we don't introduce regressions 🙏 Thanks for your patience!

**Pull request merged**
