### PR TITLE
[KEEP OPEN] Update French Translation (Now in Crowdin)

### PR DESCRIPTION
**Pull request by Makazzz**
### Description

I updated the french translation for the latest update (5.3.4-beta.4) and I merged everything new from the en-US.json file.
### Motivation and Context

My goal is to have the translation up to date for french.
### How Has This Been Tested?

I will wait to see the appveyor build.
### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist:

- [ ] My code follows the code style of this project (run `$ yarn lint`).

### CODE REVIEW

**Comment by vantezzen** [comment]
Thank you very much! Should be able to merge when all checks are done.

Additionally, I am currently in the process of setting up a CrowdIn project for Ferdi so all translations can be crowd-sourced.

**Comment by Makazzz** [comment]
Thanks I am testing it but I saw that some of the texte are still not translate. I will investigate.

**Comment by Makazzz** [comment]
Ok so everything seems good but in the settings there is some text that can't be translated because this text are in the [EditSettingsForm.js](https://github.com/getferdi/ferdi/blob/master/src/components/settings/settings/EditSettingsForm.js)

**Comment by vantezzen** [comment]
> Ok so everything seems good but in the settings there is some text that can't be translated because this text are in the [EditSettingsForm.js](https://github.com/getferdi/ferdi/blob/master/src/components/settings/settings/EditSettingsForm.js)

Oh, looks like I missed some texts while converting to i18n texts. I'll fix this.

**Comment by Makazzz** [comment]
> I now added the texts to i18n via [b65b334](https://github.com/getferdi/ferdi/commit/b65b3344163248feb316047ad9b70120db84e396). Could you add those texts to your translation?

At the line 257 you put for `settings.app.serverMoneyInfo`  
**"You are using the official Ferdi Server for Ferdi."**  
but at the line 43 in EditSettingsForm.json it is saying  
**"You are using the official _Franz_ Server for Ferdi"**

**Comment by Makazzz** [comment]
I did the test and everything is now translated unless one thing wich is where it is saying about Ferdi being bades on Franz in Apache 2.0 license [at the line 434](https://github.com/getferdi/ferdi/blob/master/src/components/settings/settings/EditSettingsForm.js#L434).

So can you do the same thing but for this too please?

**Comment by vantezzen** [comment]
> > I now added the texts to i18n via [b65b334](https://github.com/getferdi/ferdi/commit/b65b3344163248feb316047ad9b70120db84e396). Could you add those texts to your translation?
> 
> Yes and I saw this;
> 
> At the line 257 for [en_US.json](https://github.com/getferdi/ferdi/commit/b65b3344163248feb316047ad9b70120db84e396#diff-afcbd98b826ace893f7327ae61da6de7) you put for `settings.app.serverMoneyInfo`
> **"You are using the official Ferdi Server for Ferdi."**
> **"...for free but you are still using Ferdi's server resources - which Ferdi's creator has to pay for."**
> **".\nPlease still consider [Link 1]paying for a Ferdi account[/Link]"**
> **"...you still profit greatly from Ferdi's recipe store..."**
> but at the line 43 in [EditSettingsForm.json](https://github.com/getferdi/ferdi/commit/b65b3344163248feb316047ad9b70120db84e396#diff-dd7bf3207a1a718a76722729ca611626) it is saying
> **"You are using the official _Franz_ Server for Ferdi"**
> "**...for free but you are still using _Franz's_ server resources - which _Franz's_ creator has to pay for."**
> **".\nPlease still consider [Link 1]paying for a _Franz_ account[/Link]"**
> **"...you still profit greatly from _Franz's_ recipe store..."**

Yes, this is a bug introduced by the apply-branding script. I have now added this key to the ignore list via 44c52de - the right text is the one from `EditSettingsForm.json`.

**Comment by Makazzz** [comment]
Ok I translated everything in [Crowdin for Ferdi](https://crowdin.com/project/getferdi) so this merge is outdated and not the good one anymore.

**Comment by vantezzen** [comment]
I'll keep this PR open as it is currently unclear whether we'll keep CrowdIn. CrowdIn advertises that it is free for OSS, but they havn't yet accepted my request - this is why the getferdi CrowdIn is currently only in CorwdIn's trial period and may run out after that.

**Comment by Makazzz** [comment]
Ok I will do some fix in this merge when I come home.

**Comment by Makazzz** [comment]
@vantezzen Do we keep Crowdin? I saw that you merge my change from Crowdin into the develop branch so that mean that I can close this Pull Request?

**Comment by vantezzen** [comment]
Crowdin still hasn't Approved my request so I can't say if we'll keep it.
I can however close this PR now as the changes have been merged via Crowdin

**Pull request closed without merging**
