### PR TITLE
Delete service confirmation

### PR DESCRIPTION
**Pull request by vraravam**
### Description
Ask for confirmation when deleting a service from the context menu of the side navbar

### Motivation and Context
As described in #1286 

### Screenshots
Screen Shot 2021-05-01 at 11 58 39 AM

### Checklist:

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`$ npm run lint`)
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Comment by kris7t** [comment]
Based on the screenshot, something looks wrong with the location: I'm pretty sure the `!!!` in the beginning of the message shouldn't be visible on the UI (it probably just marks a localizable string).

Also, I think it would be good practice to base this branch on `develop` instead of #1326 (although if we merge them in order, it wouldn't really matter).

**Comment by vraravam** [comment]
@kris7t - I just copy-pasted the exact string from another similar message in the same file. (I also noticed that the `!!!` are replaced by some script while packaging the app - which I might have missed as I was bulding for use in my local). Please disregard that for now.

I have removed the other 2 commits that were in #1326 - so that this PR is atomic.

For the name of the service, let me check if i can do it quickly.

**Comment by vraravam** [comment]
@kris7t pushed a new commit - and this is how it looks now:
Screen Shot 2021-05-01 at 10 00 01 PM

**Comment by kris7t** [comment]
I never tried to do this, so my assumption could be a bit naive, but maybe the new message should be added to `src/i18n/locales/en-US.json` in addition to `src/i18n/messages/src/components/services/tabs/TabItem.json`? It looks like the `!!!` is there to mark untranslated strings (so the default message with the `!!!` would be displayed until the translation is added on Crowdin for the other locales).

**Comment by vraravam** [comment]
I am also not sure of what to do to trigger the crowdin translator to pick up the keys. I have pushed a new commit with this as per your suggestion.

**Comment by vraravam** [comment]
@kris7t - you are right sir. Adding that key into the `src/i18n/locales/en-US.json` caused the `!!!` to get removed!
Screen Shot 2021-05-01 at 10 46 36 PM

**Comment by kris7t** [comment]
I too wonder how to properly make Crowdin recognize this -- maybe @kytwb could help?

**Comment by vraravam** [comment]
Looking through `crowdin.yml` - its exactly like what you outlined: the `en-US.yml` is taken as the template, and other 2-character locale codes are generated for the same keys by a bot. This process kicks in once this gets merged into the `develop` branch I suppose.

cc @kytwb - is this correct?

**Comment by kris7t** [comment]
Looks good to me.

**Comment by kytwb** [comment]
@vraravam this sound correct 👍 thanks!

@all-contributors please add @kris7t for review

**Pull request merged**
