### PR TITLE
Add setting to enable nightly releases updates

### PR DESCRIPTION
**Pull request by vantezzen**
### Description
#730 already set up the nightly pipeline. This PR will add a new "Use nightly releases" toggle to switch the electron-updater to the nightly repository.

It will also show a popup warning about nightly releases before switching so unexperienced users won't accidentally switch.

### Checklist:

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`$ npm run lint`)
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Comment by kytwb** [comment]
Thank you for taking care of this @vantezzen 🙏 
I have been a bit confused to see the updater working since I have switched to the nightlies manually - see https://github.com/getferdi/ferdi/issues/329#issuecomment-626537218. I am not sure how, given `setFeedURL` for getferdi/nightlies is made available in this pull request only. Could you please help me clarify this?

**Comment by vantezzen** [comment]
I also don't know why the updater was working - it shouldn't even look in the nightlies repository (or have you changes something manually there?)

**Comment by kytwb** [comment]
I was looking at the [wrong documentation](https://www.electronjs.org/docs/api/auto-updater). 
We are using [`autoUpdater`](https://www.electron.build/auto-update#quick-setup-guide) from `electron-updater`, not from `electron`:

> Do not call setFeedURL. electron-builder automatically creates app-update.yml file for you on build in the resources (this file is internal, you don’t need to be aware of it).

**Comment by kytwb** [comment]
I think there is a small issue with the UX; after choosing Activate or Cancel in the modal, the user isn't redirected properly to the update tab which is a little bit confusing:

Kapture 2020-05-16 at 18 29 39

It seems the settings screen is being closed when the modal is shown. What do you think of moving the confirmation part below the `ToggleRaw`?

**Comment by kytwb** [comment]
There is a bigger issue which I am not sure we should address in this pull request or not; I think with `electron-updater`, calling `setFeedURL` has no effect, so maybe going back to using `autoUpdater` from `electron` and explicitly calling it for every cases would be a solution? I am not sure why we're using the one from `electron-updater` in the first place.

**Comment by vantezzen** [comment]
We're using `electron-updater` because Franz uses it, too - I don't think there are any other reasons behind this.
It seems like Electron has a good method for updating, too (https://www.electronjs.org/docs/tutorial/updates). Should we switch to that instead? Maybe that will also fix the update problems.

**Review by kytwb — APPROVED** [review]

**Comment by kytwb** [comment]
@vantezzen Let's address the auto-updater issue (if any) in another pull request.

We can improve the UX via https://github.com/getferdi/ferdi/pull/977 if needed.

**Comment by vantezzen** [comment]
Yes, that sounds good.

**Pull request merged**
