### PR TITLE
Removed electron-process-manager since its no longer supported by Ele…

### PR DESCRIPTION
**Pull request by vraravam**
…ctron

### Description
Removing ProcessManager

### Motivation and Context
Chromium/Electron no longer support these modules/APIs. Since we have moved to Electron 11 (and soon to 12 as well) - it was discussed in #1296 to go ahead and remove these.

### Checklist:

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`$ npm run lint`)
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Comment by kris7t** [comment]
Works fine for me (or, to be more precise, I have no process manager button any more).

We should probably merge this before #1308 and I'll rebase that one again, otherwise, you'll have to rebase this due to a merge conflict in `package-lock.json`, I think.

**Comment by vraravam** [comment]
thanks @kris7t .
@kytwb @vantezzen - can one of you please do the honors?

**Comment by kytwb** [comment]
@vraravam thanks!

**Comment by kytwb** [comment]
@all-contributors please add @vraravam for code

**Pull request merged**
