### PR TITLE
Implement user.css and user.js

### PR DESCRIPTION
**Pull request by vantezzen**
This PR will add custom user styles and scripts as requested in #83.

For more information about the usage of this feature, see https://github.com/getferdi/ferdi/wiki/Using-user.css-and-user.js

### CODE REVIEW

**Comment by kytwb** [comment]
https://github.com/getferdi/ferdi/wiki/Using-user.css-and-user.js#moduleexports Well done! 👍

**Comment by kytwb** [comment]
It worked once, but it's not working anymore. Investigating.

**Comment by kytwb** [comment]
I suspect the following not to be triggered every time:

https://github.com/getferdi/ferdi/blob/fb6766dc85c80e1297e165af32a8fd2cb79367b4/src/webview/recipe.js#L118

**Comment by vantezzen** [comment]
If that's the reason then we can just remove the listener and directly require the script instead, I just thought it might be more useful for scripts to only be loaded once the DOM is ready.

**Comment by kytwb** [comment]
I don't mind removing the event handler and let users deal with the window/document/available objects. Otherwise, I found using `document.onreadystatechange` to be more reliable (via https://stackoverflow.com/a/59664269/926721).

**Comment by vantezzen** [comment]
2bb79d9e should now have fixed this issue, can you test that?

**Comment by n-st** [comment]
> For more information about the usage of this feature, see https://github.com/getferdi/ferdi/wiki/Using-user.css-and-user.js

For the record, the documentation has been moved to https://help.getferdi.com/features/userfiles.

**Comment by hcientist** [comment]
where should I see the log statement for the example (i.e. [`Hello, World!`](https://help.getferdi.com/features/userfiles#User.js))? I hit <kbd>cmd</kbd>+<kbd>opt</kbd>+<kbd>i</kbd> and despite having the source below, I never see my logs 🤔

```
module.exports = (config, Ferdi) => {
  // Write your scripts here
  console.log('Hello, World!', config)
  let betterListener = (str) => (ev) => {
    console.log(str, 'ev', ev)
  }
  let i = 0
  setInterval(() => {
    console.log('idk', i++)
  }, 1000)

  window.addEventListener('keyup', betterListener('keyup'), true)
  window.addEventListener('keydown', betterListener('keydown'), true)
  document.addEventListener('keyup', betterListener('keyup'), true)
  document.addEventListener('keydown', betterListener('keydown'), true)
}
```

**Comment by vantezzen** [comment]
Your userscripts are run in the service view, the developer tools you have opened only show the container view.

You can open the correct devtools using `CMD + Shift + Alt + I` or in the menubar under "View" > "Toggle Service Developer Tools"

**Comment by hcientist** [comment]
Thanks @vantezzen !

**Pull request merged**
