### PR TITLE
Fix and enhance context menu

### PR DESCRIPTION
**Pull request by kytwb**
### Description
I went in to investigate https://github.com/getferdi/ferdi/issues/357#issuecomment-590804645. I could not find any reference of `getSuggestion` anywhere in the code or in electron-spellchecker, so I guess this part of the code is deprecated. Also, I noticed the contextual menu we tried to create in contextMenu() was conflicting with the default context menu handling of electron-spellchecker.

### Motivation and Context
Fixes https://github.com/getferdi/ferdi/issues/357.

### How Has This Been Tested?
Remove conflicting contextual menu handling attempt and context menu work as expected again in services. It also fixes the custom context menus in WhatsApp/Gmail it seems, I didn't notice it before maybe.

### Screenshots (if appropriate):
Screen Shot 2020-03-02 at 2 34 52 AM
Screen Shot 2020-03-02 at 2 34 56 AM
Screen Shot 2020-03-02 at 2 35 07 AM
Screen Shot 2020-03-02 at 2 35 37 AM
Screen Shot 2020-03-02 at 3 11 34 AM

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code follows the code style of this project (run `$ yarn lint`).

### CODE REVIEW

**Comment by kytwb** [comment]
Also takes care of https://github.com/getferdi/ferdi/issues/413:

Screen Shot 2020-03-02 at 3 05 09 AM

**Comment by vantezzen** [comment]
I've now added the entry "Open Link in Ferdi" (for use when Ferdi incorrectly opens links in the browser) and added some comments.

**Comment by lolmaus** [comment]
Thx! When will this be released? 🥺

**Comment by vantezzen** [comment]
It will be released with the next beta version which would normally be scheduled in 2-4 weeks - we may release a beta before that.

**Comment by lolmaus** [comment]
@vantezzen Please do. Context menus are completely broken on the latest stable version for me.

**Comment by kytwb** [comment]
@lolmaus @vantezzen I have been a bit busy these days, but I will focus on making a new beta release with the latest fixes and improvements in the coming days given the importance of the fixes and feedback we're getting 🙏 Thanks for your patience guys!

**Pull request merged**
