### PR TITLE
Use imagemin to minify images

### PR DESCRIPTION
**Pull request by vraravam**
### Description
Used `imagemin` npm package to minify all images in this repository using default settings. Since its an npm package that doesn't have a dependency on any other installed software, its more consistently runnable on any developer's machine.

### Motivation and Context
Having images in a higher size will mean that
- The git repository takes up a lot of space
- The built-up deployable/installable file will be bigger and thus will have more costs associated for storage
- The bigger-sized installer file will mean that the download artifact will also be bigger and mean more network usage
- The image optimization software reported a compression of almost 27% for the images.

### Checklist:

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`$ npm run lint`)
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Comment by vraravam** [comment]
As a suggestion, once this is merged, maybe this can be included as a pre-requisite step to be done by each PR for a recipe (so that the git repo is not bloated with multiple versions of binary image files. So, adding this to the PR template as well as the GH actions for CI as checks prior to PR approval.

**Comment by vraravam** [comment]
@kytwb - could you please review and accept this PR as well?

**Comment by kytwb** [comment]
@vraravam thank you!

Let's see in the next nightly release if it doesn't introduce visible regressions on the quality of the images.

**Comment by vraravam** [comment]
definitely - if so, we can revert - agree with you

**Comment by kytwb** [comment]
@vraravam I hadn't checked out the branch locally, I just looked at the diff on GitHub and let slip through the following:

```
kytwb@kytwbs-mbp images % ls -l icons 
total 0
-rw-r--r--  1 kytwb  staff  0 Oct 10 00:54 1024x1024.png
-rw-r--r--  1 kytwb  staff  0 Oct 10 00:54 128x128.png
-rw-r--r--@ 1 kytwb  staff  0 Oct 10 00:54 16x16.png
-rw-r--r--  1 kytwb  staff  0 Oct 10 00:54 24x24.png
-rw-r--r--  1 kytwb  staff  0 Oct 10 00:54 256x256.png
-rw-r--r--  1 kytwb  staff  0 Oct 10 00:54 32x32.png
-rw-r--r--  1 kytwb  staff  0 Oct 10 00:54 48x48.png
-rw-r--r--@ 1 kytwb  staff  0 Oct 10 00:54 512x512.png
-rw-r--r--  1 kytwb  staff  0 Oct 10 00:54 64x64.png
-rw-r--r--  1 kytwb  staff  0 Oct 10 00:54 96x96.png
kytwb@kytwbs-mbp images % pwd
/Users/kytwb/Projects/Ferdi/ferdi/build-helpers/images
```

A couple of assets are now empty.  
I am reverting the squash merge on develop for now.

**Pull request merged**
