### PR TITLE
Implementing Window Icon

### LINKED ISSUE #182: Add window icon
Would be nice if Ferdi included window icon, so it's easier to identify in window titles.
Useful in some (tiling) windowmangers in stacked or tabbed layouts, where only titlebars may be visible.

### PR DESCRIPTION
**Pull request by eminokic**
#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has _stopped working_ or is _working incorrectly_, please log the bug [here](https://github.com/getferdi/recipes/issues)
2. If you are requesting support for a **new service** in Ferdi, please log it [here](https://github.com/getferdi/recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdi, but to get new recipes between Ferdi releases, this documentation is quite useful.)
4. Please consider supporting Ferdi!
  👉 https://github.com/sponsors/getferdi
  👉 https://opencollective.com/getferdi/donate
5. Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

#### Motivation and Context
Fixes #182 

#### Checklist

- [x] My pull request is properly named
- [ ] The changes respect the code style of the project (`npm run prepare-code`)
- [ ] `npm test` passes
- [ ] I tested/previewed my changes locally

### CODE REVIEW

**Comment by eminokic** [comment]
@laur89 @vraravam Can you check this for me, and could I possibly learn more about your debugging / testing workflow for when you try to run new mods. I assume the last command on the contributor's guide works correctly and it is just on my part though I would like to be sure.

**Comment by eminokic** [comment]
@vraravam It is sadly not complete. I was going to use that current icon as a place holder while I use my aesprite trial to potentially write another one. Is there a way you setup that original picture as an alternate I can switch the url to to test the desig? 
Also, on ubuntu it is not loading the logo, though the window icon formatting does look better than before. I am not sure why it is not drawing on that I'll have to look into that tomorrow. It may require me analyzing the class design a little further.

**Comment by eminokic** [comment]
@vraravam Also, if you don't mind, what is the typical process / workflow you run of commands to make sure your branch is up to date? I get a bit confused on that sometimes.

**Comment by eminokic** [comment]
A few more resources I'll look at later that may be some leads. 

https://github.com/electron/electron-packager/issues/128

https://github.com/jlord/git-it-electron/blob/master/main.js#L29

**Comment by vraravam** [comment]
> @vraravam It is sadly not complete. I was going to use that current icon as a place holder while I use my aesprite trial to potentially write another one.
Unfortunately, the designs would need a larger approval process (imo), so, its better to use graphics that are already in use. Changing the icons can be a separate PR. Please start a discussion thread for it - when you are ready with the new icon.


> @vraravam Also, if you don't mind, what is the typical process / workflow you run of commands to make sure your branch is up to date? I get a bit confused on that sometimes.

I use the [following command](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md#start-development-app) to run it in debug mode.

**Comment by eminokic** [comment]
@vraravam I can't seem to figure it out. I tried approaching it differently, but the I fell back to that same implementation we had before the review. Here is another resource I have been looking at. At the top left no icon shows up, yet at the top right the mustache shows up. I am not sure if that is because I set the logo as a png instead of ico image for the electron build. 
I have also read that you may have to explicitly set --icon as the image path but am not too familiar with electron to make that decision. 
Do you happen to have any resources on learning more about electron? I think that would help.

Reference: https://stackoverflow.com/questions/31529772/how-to-set-app-icon-for-electron-atom-shell-app

**Comment by eminokic** [comment]
@vraravam I am working on a modular component in a separate repository to try and see where the code is required for implementing a window icon in linux's panel icons. The code here works as needed, though the icon does not display on the top left side but does on the top right just fine. Thus, I think this is a deeper issue, and can write that up before continuing the next PR. Please let me know if we can send this to merge, and if you'd like to be attached to the repository on the window icon as I develop it.

**Comment by vraravam** [comment]
thanks @eminokic - could you please share a screenshot? That way, we can also have @mhatvan chime in whether this is ready for merge. (I dont use linux, and so this change does not affect me)

**Comment by vraravam** [comment]
@eminokic - since there's no word from you, should we mark this PR as abandoned?

**Comment by vraravam** [comment]
@eminokic - closing this Pr since there's no response about progress. Thanks for your contributions.

**Pull request closed without merging**
