### PR TITLE
Use useragent generator

### PR DESCRIPTION
**Pull request by vraravam**
### Description
Use `useragent-generator` to generate the user-agent string rather than building it by hand.

Marking as "draft" till [this other PR](https://github.com/getferdi/ferdi/pull/1591) gets approved and merged

### Motivation and Context
This is from the [following conversation](https://github.com/getferdi/ferdi/pull/1380#issuecomment-860531708). Intention/motivation is to avoid hardcoding - so that, as we upgrade electron (and thus chromium) versions, we can rest-assured that functionalities will continue to work.

### Checklist:

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`$ npm run lint && npm run reformat-files && npm run manage-translations && npm run apply-branding`)
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Comment by mhatvan** [comment]
In general, I approve using a lib to avoid building it by hand but https://github.com/pastelsky/useragent-generator didn't receive any updates in ~3 years. This means that we will have super old (maybe vulnerable) subdependency versions that `useragent-generator` depends on.

Unfortunately I didn't find any good alternative to `useragent-generator` on npm based on a quick search.

**Comment by vraravam** [comment]
Yes @mhatvan: I looked through other alternatives for ua-generation - none of them seemed to be actively maintained. This one seemed to have the most recent commit.

**Comment by vraravam** [comment]
@kris7t - any ideas? or shall I proceed with merging this PR?

**Comment by kris7t** [comment]
It's still quite strange that that `ua-generator` defaults to Windows as the OS. So we might need to write our own alternative library instead.

Plus, if I see correctly, `ua-generator` can't really help us with tracking the latest versions of browsers (since it's unmaintained). So we'll need some other tool to let users say, e.g., `last Firefox on Linux`, and generate an UA string with the latest version of Firefox running on Linux (while, say, `last Firefox` would result in the Firefox UA, but with the actual OS Ferdi is running on). Maybe something like `browserlist` could help there instead?

**Comment by vraravam** [comment]
I tried looking through the `browserslist` npm module and the `caniuse-lite` one that **it** depends on. Though the intended use (public methods API) is similar to what we want at the end of this PR, there's nothing similar in either of these 2 npm modules that can be hooked up easily. Also, as @kris7t described it, there might need to be UI changes that take the user's choice, and translate/parse it into what `browserslist` or `caniuse-lite` can then be called with. This seems very tedious at this point (at least for me).

**Comment by vraravam** [comment]
@kris7t - please confirm if your 👍🏼 for the above comment means that we can merge this PR? Or whether you are going to take a stab at it later this week/next when you get a chance? If the former, I will remove the "draft" flag and you can approve this. If the latter, then I will close the PR as abandoned.

**Comment by vraravam** [comment]
@kris7t : Based on your comment above - I took a look at the useragent-generator` repo. The additions for newer configs seem simple enough. I will take a crack at it today. If we have a newer version, and while waiting for the PR to be accepted by the original author (and subsequent publishing into npmjs.com), I am thinking of pointing to my GH fork url in ferdi's `package.json`. Would this be acceptable for now?

**Comment by kris7t** [comment]
Yeah, I guess we should use our own fork for `useragent-generator` (at the very least, for generating UA strings with the proper OS) if upstream doesn't support it.

**Comment by vraravam** [comment]
@kris7t - i have reverted parts of the previous commit - to be able to get the closest user-agent string for my macos. Guessed the same for windows and lonux - based on the `user-agent-switcher` FF plugin for different OSes and versions..

(Please review and approve. I will squash while merging the PR into a single commit.)

**Review by kris7t — APPROVED** [review]

**Pull request merged**
