### PR TITLE
chore: get rid of various decorators

### PR DESCRIPTION
**Pull request by mhatvan**
#### Description of Change
- upgrade `mobx-react` to 6.3.1 and `mobx-react-form` to 2.0.9
- removed non-standard decorators with `npx mobx-undecorate`
- updated `Form.ts` plugins due to `mobx-react-form` upgrade
- untangled `wrappedComponent.propTypes`
- fixed `mdi-eye` icon issues in `Input.js`
- fixed `RecipesDashboard` breaking on certain user input
- removed stray `console.logs`

#### Motivation and Context
We need to move away from non-standard decorators since they produce various issues.

The chained HOC syntax how it looks now is really ugly, but it is just an intermediary step to migrate to React hooks.

This PR is also a good step into the right direction to be able to upgrade `mobx` and `react-jss` eventually.

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`npm run prepare-code`)
- [x] `npm test` passes
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Review by vraravam — APPROVED** [review]
I haven't tested this locally, but the changes seem good.

**Comment by vraravam** [comment]
Unfortunately, this did not work in production/packaged mode

**Comment by vraravam** [comment]
after a lot of trial and error, finally figured out what's causing this to fail: if you use Ferdi with a pre-existing profile, and in that profile's `config/settings.json`, if you have the `lockingFeatureEnabled` turned on (ie true), then this branch fails. Can you please verify by setting a new value for the master password, and restart Ferdi? I have verified that this fails consistently and the restart of Ferdi results in a blank screen without the login screen showing up

**Comment by mhatvan** [comment]
Superseded by https://github.com/getferdi/ferdi/pull/2302 (which includes this PRs changes)

**Pull request closed without merging**
