### PR TITLE
fix: icon alignment for horizontal bar

### LINKED ISSUE #2041: Icons not alligned when using Horizontal bar
**Bug description:**
Icons on sidebar are not aligned when using horizontal bar

**Steps to reproduce:**

Change side bard to Horizontal

**Expected behavior**
Icons should be aligned same way as they are when the bar is on the side. 

**Screenshots**
Top: 
topBar

Side:
SideBar

**Environment:**

- Operating System: Arch Linux
- Ferdi Version: 5.6.3.nightly.27

Hope the info provided is enough, feel free to request any more info, ill be glad to provide it.

### PR DESCRIPTION
**Pull request by balajiv113**
#### Description of Change

Fix for the improper icon alignment for horizontal bar

#### Motivation and Context

Fixes #2041
The sidebar horizontal height issue is already fixed as part of #2169 

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`npm run prepare-code`)
- [x] `npm test` passes
- [x] I tested/previewed my changes locally

#### Screenshots of fix
**Normal Icon and normal sidebar**
Screenshot 2021-11-03 at 10 23 06 AM

**Normal Icon and very slim sidebar**
Screenshot 2021-11-03 at 10 23 21 AM

**Very small Icon and normal sidebar**
Screenshot 2021-11-03 at 10 23 40 AM

### CODE REVIEW

**Comment by vraravam** [comment]
@balajiv113 - is this ready for review?

**Comment by balajiv113** [comment]
Yes, it is ready for review

**Comment by vraravam** [comment]
Can you please post screenshots of the vertical layout? That would enable me to approve this PR as-is.

**Comment by balajiv113** [comment]
Screenshots of vertical layout. Sure, Will join the gitter channel as well.

**Normal Icon and normal sidebar**
Screenshot 2021-11-09 at 10 52 32 AM

**Normal Icon and very slim sidebar**
Screenshot 2021-11-09 at 10 53 28 AM

**Very small Icon and normal sidebar**
Screenshot 2021-11-09 at 10 53 50 AM

**Review by vraravam — APPROVED** [review]
thanks for the screenshots. LGTM

**Pull request merged**
