### PR TITLE
Upgrade npm modules

### PR DESCRIPTION
**Pull request by vraravam**
### Description
Keeping up-to-date with npm modules. Ran `npm outdated` to figure out the packages that need this love - and only upgrading dev dependencies for now.

### Motivation and Context
Keep up-to-date

### Checklist:

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`$ npm run lint`)
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Comment by vraravam** [comment]
@kris7t - since you are on AUR, could you please test this when you get a chance? I am running all my tests on macOS till now.

**Comment by kris7t** [comment]
Is it supposed the rebuild the whole Electron application on `npm run start`? Back when we were using `electron-rebuild`, I think `npm run start` was a fairly quick operation to enable rapid iterations when developing, but now I have to wait until it builds AppImage and rpm packages. This turns a several-second start into a several-minute one.

**Comment by vraravam** [comment]
@kris7t - can you please revert (locally) 2b41eb1 - and try if it goes back to your earlier expected behavior?

**Comment by kris7t** [comment]
I'm trying to revert -- but after the version bump on `prettier`, my current setup for building the Ferdi package locally for arch (involving a circular symlink... long story) the git pre-commit code formatting hook seems to go absolutely crazy. Okay, that's probably my fault for playing around with symlinks.

**Comment by vraravam** [comment]
Can you try with the `--no-verify` while reverting? If this revert fixes your issue - I will remove that commit from the mix

**Comment by kris7t** [comment]
Indeed, reverting 2b41eb1ff247cde47cce95604989c141109fb013 restored the expected behavior.

**Comment by vraravam** [comment]
Great - let me remove that commit from the mix. tx for teting @kris7t

**Comment by vraravam** [comment]
done @kris7t - in case you want to pull again and test quickly.

**Comment by kris7t** [comment]
Seems working fine now.

I'm getting some warnings about peer dependencies in

```
npm WARN @meetfranz/forms@1.2.1 requires a peer of react-dom@16.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN @meetfranz/ui@1.1.0 requires a peer of react-dom@16.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN @octokit/plugin-request-log@1.0.3 requires a peer of @octokit/core@>=3 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb-base@13.2.0 requires a peer of eslint-plugin-import@^2.17.2 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-loader@1.9.0 requires a peer of eslint@>=1.6.0 <5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN mobx-react-router@3.1.2 requires a peer of mobx@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-addons-css-transition-group@15.6.2 requires a peer of react@^15.4.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-dom@16.14.0 requires a peer of react@^16.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-electron-web-view@2.0.1 requires a peer of react@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-electron-web-view@2.0.1 requires a peer of react-dom@^15.0.0 but none is installed. You must install peer dependencies yourself.
```

but I don't really know how to fix them (maybe bumping the `pacakges/*/package.json` files would be enough?). Nevertheless, they don't seem to cause any issues.

**Pull request merged**
