### PR TITLE
Add modifyRequestHeaders, enable properly setting headers for services

### LINKED ISSUE #621: Searching for a user doesnt work in Google Chat
**Describe the bug**

Searching for a user doesn't work in Google chat  
Search for a user who is not in the cached list of Google Chat. 
**To Reproduce**

1. Go to Google Chat and search for a user using the search bar on the top left panel
2. Type in a few words and observe that no results are returned

**Expected behavior**

Matching users should be listed in the dropdown.

**Screenshots**
Look for the autocomplete requests failing in the console

image

Here is a response of the autocomplete request:
`{
  "error": {
    "code": 401,
    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED"
  }
}
`
**Desktop:**

- OS: [Windows 10]
- Ferdi Version [e.g. 5.4.3]
- Server Used: [e.g. https://api.getferdi.com]

### PR DESCRIPTION
**Pull request by sampathBlam**
Co-Authored-By: Mahadevan Sreenivasan <mahadevan_sv@yahoo.com>

Fixed the issue in User search functionality of Hangouts Chat by adding `origin` header to the requests sent. (This issue is present in both the search bar as well as the 'Add Member' dialog of a Room).

### Description

- `Origin` header was not being sent in the requests that searches users using Google APIs from Ferdi's webview.
- Add ability for recipes to add headers in any ongoing request from their respective webviews.
- Add headers for specific patterns of urls. This can be used to send different headers for different URLs in a recipe's context.
-  Add check to identify if the method `modifyRequestHeaders` is implemented by recipes.
- Send IPC message from models/Service.js to the main process to set the headers if the method is implemented
- Receive the IPC message in index.js and add headers using `session.fromPartition(<PartitionName>).webRequest.onBeforeSendHeaders` method
- Changes to the Hangouts Chat recipe  have been added to the corresponding repo. 
- Created PR in that repository getferdi/recipes#137 

### Motivation and Context

- Fixes #621 once the changes from getferdi/recipes#137 are merged as well.

### How Has This Been Tested?

Tested in local windows dev environment.
Ferdi version 5.5.0-gm.2

### Before

image

### After

image

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist:

- [x] My code follows the code style of this project (run `$ npm run lint`).

### CODE REVIEW

**Comment by kytwb** [comment]
@sampathBlam 

@mahadevans87 I think this is because there is a `environment` declared in appveyor.yml, which must take priority over the environment variables I set through AppVeyor dashboard. I will address, can ignore for now 🙏

**Comment by kytwb** [comment]
@mahadevans87 Erratum: I think it was because it is a pull request coming from an external repository, environment variables are not shared in that case otherwise you could `console.log(process.env)` in your pull request to retrieve the CI secrets.

**Comment by kytwb** [comment]
@mahadevans87 Erratum 2 😅 Looks like it was a mix of the two? https://github.com/getferdi/ferdi/pull/641#issuecomment-619171713

**Comment by sampathBlam** [comment]
@kytwb : Is it possible to add this to the list of features in the 5.5.0 release change log ?

**Comment by kytwb** [comment]
@sampathBlam Yes, my bad, that slipped through as well! That is why I will really focus on the automation of semantic releases 😋

**Comment by kytwb** [comment]
@all-contributors please add sampathBlam for ideas

**Pull request merged**
