### PR TITLE
Sign and notarize deliverable for macOS

### PR DESCRIPTION
**Pull request by kytwb**
For https://github.com/kytwb/ferdi/issues/35

### CODE REVIEW

**Comment by kytwb** [comment]
@vantezzen I think we want the notarization step to happen only on tags builds, same as Travis deploy and electron-builder publish?

**Comment by vantezzen** [comment]
> electron-builder publish

Yes

**Comment by vantezzen** [comment]
I think you'll need to add the [Apple Events Entitlement](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_automation_apple-events), Ferdi uses the [applescript](https://www.npmjs.com/package/applescript) package that requires this.
Screenshot
 
Ferdi may also require the [Audio Input Entitlement](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_device_audio-input) and [Camera Entitlement](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_device_camera) to enable services like Skype to work - but I am not sure about this.

Other than that, this PR looks good.

**Comment by kytwb** [comment]
I haven't been able to confirm things are working as the built app doesn't open anymore in my local (opening it and it closes right away, no crash report). Pushing things as they are in my local and will continue tomorrow!

**Comment by kytwb** [comment]
Back to troubleshooting this; it's similar to https://github.com/electron-userland/electron-builder/issues/3989 I think (or Google Search on _"signed app crash electron"_).

**Comment by kytwb** [comment]
Managed to run the app while just signed after upgrading the dependencies. Trying again with a signed and notarized one and merging if it works. Will give it a test run to make sure to fix the regressions if any.

**Pull request merged**
