### PR TITLE
Add a confirmation when quitting Ferdi and a preference to toggle it (implements #1857)

### LINKED ISSUE #1857: Disable Ctrl+Q shotrcut that quits Ferdi without any question
**Is your feature request related to a problem? Please describe.**
Sometimes I accidentally press the `Ctrl+Q` keyboard combination, that's immediately closes the Ferdi app without any questions or confirmations, and I can't find the way to disable this shortcut or enable confirmation of this action.

**Describe the solution you'd like**
Will be glad to have a configuration of all keyboard shortcuts, but this is a large task. So will be good have an option to disable this hotkey only, or maybe add confirmation "Are you sure want to exit Ferdi?" dialog.

### PR DESCRIPTION
**Pull request by vraravam**
#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has *stopped working* or is *working incorrectly*, please log the bug [here](https://github.com/getferdi/recipes/issues)
2. If you are requesting support for a **new service** in Ferdi, please log it [here](https://github.com/getferdi/recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdi, but to get new recipes between Ferdi releases, this documentation is quite useful.)
4. Please consider supporting Ferdi!
  👉  https://github.com/sponsors/getferdi
  👉  https://opencollective.com/getferdi/donate
5. Please ensure you've completed all of the following.
- [x] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change
Adds a preference to ask for confirmation when quitting Ferdi.

Also removed the redundant `role` for the quit menu item - since its presence overrides the custom click-event-handler.

#### Motivation and Context
Fixes #1857 

#### Screenshots
Screenshot 2021-09-07 at 3 22 22 PM
Screenshot 2021-09-07 at 3 23 05 PM

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`npm run prepare-code`)
- [x] `npm test` passes
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Comment by sad270** [comment]
I try this on macOS, it works when you quite with cmd+Q or menu `Ferdi > Quit`  or from Systray icon > Quit
But not when you disable `Keep Ferdi in background when closing the window` and you click on the red `x` to close window.

**Review by mhatvan — APPROVED** [review]

**Comment by vraravam** [comment]
> I try this on macOS, it works when you quite with cmd+Q or menu `Ferdi > Quit` or from Systray icon > Quit
> But not when you disable `Keep Ferdi in background when closing the window` and you click on the red `x` to close window.

@sad270 - please check the latest commit that I have done. I'm not able to test this extra condition on macos. If you can test, please go ahead. I would much rather take the #1857 at face-value and NOT use the 3rd commit. Please advice.

**Comment by sad270** [comment]
The `x` button still not working.
If you can't test, I can watch how to make it work on macOS later
We can merge this PR and create a new issue for the `x` button assigned to me. Or not merge now wait for my fix in this PR and merge with the fix ?

**Comment by vraravam** [comment]
Let me revert my last commit - and merge this PR. As I stated, imo, this fixed the issue reported by the OP of #1857 . For the other behavior that you raised, please raise a new PR. (Hint - just search for `app.quit()` in the whole codebase.

**Review by sad270 — APPROVED** [review]

**Comment by vraravam** [comment]
@sad270 - please join the gitter channel (link in the `README`) for more impromptu conversations with the rest of the contributors

**Pull request merged**
