### PR TITLE
chore: upgrade 'electron-builder' to '22.14.6' and 'electron-updater' to '4.6.2'

### PR DESCRIPTION
**Pull request by vraravam**
#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has _stopped working_ or is _working incorrectly_, please log the bug [here](https://github.com/getferdi/recipes/issues)
2. If you are requesting support for a **new service** in Ferdi, please log it [here](https://github.com/getferdi/recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdi, but to get new recipes between Ferdi releases, this documentation is quite useful.)
4. Please consider supporting Ferdi!
  👉 https://github.com/sponsors/getferdi
  👉 https://opencollective.com/getferdi/donate
5. Please ensure you've completed all of the following.

- [x] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change
Upgraded `electron-builder` to `22.14.6` (pre-release) and  `electron-updater` to `4.6.2`

#### Motivation and Context
According to the [release notes](https://github.com/electron-userland/electron-builder/releases/tag/v22.14.6) it fixes the in-app updater in #329 (🤞)
_Note_: I'm not sure if this can be tested with the current nightly version of Ferdi or whether we will need this PR to be merged and released and THEN look to see the update sequence.

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`npm run prepare-code`)
- [x] `npm test` passes
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Review by mhatvan — APPROVED** [review]
Would be amazing if that fixes the auto updater!

**Comment by balajiv113** [comment]
We should also update electron-updater package to electron-updater@4.6.2

https://github.com/electron-userland/electron-builder/pull/6390#issuecomment-963825619

**Comment by vraravam** [comment]
> We should also update electron-updater package to electron-updater@4.6.2
> 
> [electron-userland/electron-builder#6390 (comment)](https://github.com/electron-userland/electron-builder/pull/6390#issuecomment-963825619)

Unfortunately, that breaks the CI builds. Reverting the last commit.

**Comment by vraravam** [comment]
ok - the issue on the windows build agent seems to not be related to these changes. Thus, merging this PR with both the upgrades (at least it'll allow the contributors to test by building locally)

**Pull request merged**
