### PR TITLE
Develop service link

### PR DESCRIPTION
**Pull request by gmarec**
Be able to open an url from a service into another service
Be able to open an url from Todo into another service

### Description
Add a service-window listener

### Motivation and Context
This prevent if correctly configured to go out of Ferdi
https://github.com/getferdi/ferdi/issues/451

### How Has This Been Tested?
Tested on mac OS X with some custom websites.
Need to use user.js to tranform all target _blank link for a specific service to another.

### Example : 
You have a Trello Service named : "Trello" and a Slack service named : "Slack" and you want to go into Trello tab when a Slack message contains a Trello link.

You need to transform via user.js all : 
<a href="https://www.trello.com/blah" target="_blank">Blah</a>

BY
<a href="javascript:window.open('https://www.trello.com/blah', 'Ferdi: Trello', 'Trello');"

OR
<a href="javascript:window.open('https://www.trello.com/blah', 'Ferdi: ServiceName', 'ServiceName');"
WHERE
ServiceName is the name of your Service.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist:
- [x ] My code follows the code style of this project (run `$ yarn lint`).
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by vantezzen** [comment]
What exactly is the code I'd have to put into `user.js`?
If I understand this correctly, this doesn't automatically detect if you have a service that accepts that URL but rather you'd have to implement this into every service's `user.js`? That doesn't sound convenient at all and I don't think many people would ever use it.
 Instead, we should check if any opened link in a service matches the base URL of another service, e.g.

https://github.com/getferdi/recipes/blob/cd5adf64fa89ab766961dc8468b19db906c93201/uncompressed/asana/package.json#L10

Then we should display a popup asking the user if (s)he wants to open that link in that service or in the browser.

**Comment by gmarec** [comment]
@vantezzen I can transform the code and detect which service use which url, but it will cause problem if a user have multiple instance of a service for example if you have 2 asana account in two different service I cannot know if I have to open it in the first one or in the other one.
For my usage, it will be ok because I've only one instance of each service. Perhaps it will more convenient to have 2 solutions with a global settings, AutoDetect Linked Service (true, false).
Let me know your preferences.

**Comment by vantezzen** [comment]
As suggested in my first comment, I had suggested to show a pop-up to the user asking what to do. This pop-up could have multiple buttons, one for each possible service name (e.g. "Open in 'Asana Work'", "Open in 'Asana Personal'", "Open in browser"). Additionally we can keep a solution like the one you add in this PR for people who want to customize this behavior.

**Comment by gmarec** [comment]
@vantezzen ok thanks I will go on with your more complete solution.

**Comment by vraravam** [comment]
This is a wonderful addition to Ferdi - please don't make it stale.

**Pull request closed without merging**
