### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by FerdiBot**
For https://github.com/getferdi/ferdi/issues/340.

### CODE REVIEW

**Comment by kytwb** [comment]
Regex to find unexpectedly translated variables when searching in `i18n/**/*.json`:

```
\{(?!version|seconds|currency|price|name|amount|count|limit|default|plan|duration|time|service|field|license|size|length|interval)(.*)\}
```

**Comment by kytwb** [comment]
@vantezzen I'm not sure why some files are out of sync; could it be mismatching locale names for the files? I don't see many configuration options in https://crowdin.com/project/getferdi/settings#integration:



I thought about locale file names mismatch because we have 3 files for Chinese but in Crowdin there's only 2 (Traditional/Simplified).

**Comment by kytwb** [comment]
@vantezzen I am not sure why some files are out of sync. The configuration dashboard at https://crowdin.com/project/getferdi/settings#integration doesn't give much indications:

Screen Shot 2020-02-22 at 10 47 09 PM

Maybe the locale file names need an update/triage? I noticed there is three translations files related to the Chinese language when there should be two. I will double check.

**Comment by kytwb** [comment]
@vantezzen Example with f6630d0 above, while Crowdin is in that state for that string:

Screen Shot 2020-02-22 at 10 57 34 PM

**Comment by kytwb** [comment]
I apparently missed to update a Serbian string before overriding the ones I thought out-of-sync; it got reverted by the bot via f6630d0. I updated it in Crowdin but now the update doesn't seem to be picked up. @vantezzen is that something I should report to Crowdin you think?

**Comment by kytwb** [comment]
I got my answer 😄

**Comment by kytwb** [comment]
- [ ] nb-NO.json should be nb.json
- [ ] ua.json should be ru-UA.json
- [ ] zh.json should be zh-CN.json

Not sure what should be made of zh-HANT.json
Source: [Crowdin Language Codes](https://support.crowdin.com/api/language-codes/)

**Comment by vantezzen** [comment]
@kytwb We should squash merge future CrowdIn PRs as these commits really clutter the commit history.

**Comment by kytwb** [comment]
@vantezzen noted! 👌 I've also fine-tuned AppVeyor builds to skip commits containing edits on `src/i18n/locales/*.json` files only via 8a6c744f.

**Pull request merged**
