### PR TITLE
Patch getDisplayMedia for screen sharing in all services

### PR DESCRIPTION
**Pull request by gautamsi**
### Description

Inject css and js for all service to make is usable with screen share.

Seems like Skype and Teams work, but Google Meet fails as it does not even get to `getDisplaymedia` which is missing in case of electron, seems like it is testing some other api and fail

Someone has to verify with the services they like to use with this.

@kytwb I am not sure if the code style is fine, or should we even inject this globally, lets keep this PR as WIP until we finalize this.

### Motivation and Context

It lets you use screen sharing with all service that supports screen sharing. 

#463 #777

### Checklist:

- [x] My pull request is properly named
- [ ] The changes respect the code style of the project (`$ npm run lint`)
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Comment by mahadevans87** [comment]
@gautamsi I shall pull this and try this out on Google Meet. Thanks for the contrib!

**Comment by gautamsi** [comment]
@mahadevans87 any luck

**Comment by gautamsi** [comment]
that was my problem, it does not get to the point where it would try to use the missing api which we are trying to fill here.
I tried changing user agent but no help.

**Comment by agermain** [comment]
Heya @gautamsi, any progress? I'd be interested in having Discord screenshare, I assume this patch aims to cover that use case as well?

**Comment by gautamsi** [comment]
@agermain this definitely cover this issue, it is that I could not test it. 

can you try this and provide feedback please.

**Comment by agermain** [comment]
@gautamsi Pressing the "Screen" button on Discord is not responsive with your patch, plus there's no feedback on the console at all.

**Pull request merged**
