### PR TITLE
Update electron to 8.0.0

### PR DESCRIPTION
**Pull request by sergiughf**
### Fixes https://github.com/getferdi/ferdi/issues/369

If the host machine runs electron 8 currently ferdi stops working due to: 

```
Uncaught Error: Module did not self register.
```

### Description

Updates electron to 8.0.0 and electron-builder to 1.10.0 so that it also fixes:

```
An unhandled error occurred inside electron-rebuild
Could not detect abi for version 8.0.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
```

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist:

- [x] My code follows the code style of this project (run `$ yarn lint`).

### CODE REVIEW

**Comment by kytwb** [comment]
@sergiughf did you run it locally and noticed any regressions / console errors?

**Comment by sergiughf** [comment]
@kytwb Yep I ran it locally with: `npm run dev` in one window and `npm run start` in another. The app managed to boot up successfully and I can add recipes and basically pretty much use it as normal. The only errors in the console are the following:

```
instrument.ts:141 Fetch API cannot load ferdi::SERVER_NOT_LOADED/features/default. URL scheme "ferdi" is not supported.

instrument.ts:141 GET https://api.getferdi.com/v1/me/services 401

instrument.ts:141 GET https://api.getferdi.com/v1/announcements/5.4.4-beta.1 404

instrument.ts:141 GET https://dev.franzinfra.com/health 503 (Service Unavailable: Back-end server is at capacity)
```

But I am assuming these ones are because I selected to use ferdi without an account? 

The rest of them are just warnings in the console.

**Comment by kytwb** [comment]
Awesome, I'll make a review after work in my local to test with an account as well and go through the Electron 8 changelog to look for anything that could be problematic (if anything). Thank you!

**Comment by sergiughf** [comment]
Thank you @kytwb !:) Let me know if further issues pop!

**Comment by kytwb** [comment]
There is a couple of new warnings, amongst which:

```
[app] (node:85171) Electron: Loading non-context-aware native module in renderer: '/Users/kytwb/Projects/Ferdi/ferdi/node_modules/@felixrieseberg/spellchecker/build/Release/spellchecker.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
[app] (node:85142) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
```

or

```
(electron) 'webview.getWebContents()' is deprecated and will be removed. Please use 'remote.webContents.fromId(webview.getWebContentsId())' instead.
```

We can refactor as we go, seems to work on macOS with an account.

**Comment by sergiughf** [comment]
Thank you @kytwb !

**Comment by kytwb** [comment]
Thanks for your contribution! 🙏

**Comment by dpeukert** [comment]
I've gone ahead and filed issues for the changes that will have to be done at some point (#385, #386, #387) and sent a PR with one (#384 - not tested yet).

**Pull request merged**
