### PR TITLE
Removed toggles/conditionals around Franz paid plans features to make them permanently available to Ferdi users.

### PR DESCRIPTION
**Pull request by vraravam**
#### Pre-flight Checklist

1. Please remember that if you are logging a bug for some service that has *stopped working* or is *working incorrectly*, please log the bug [here](https://github.com/getferdi/recipes/issues)
2. If you are requesting support for a **new service** in Ferdi, please log it [here](https://github.com/getferdi/recipes/pulls)
3. Please remember to read the [self-help documentation](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help) - in case it helps you unblock yourself for issues related to older versions of recipes that were installed on your machine. (These will get automatically upgraded when you upgrade to the newer versions of Ferdi, but to get new recipes between Ferdi releases, this documentation is quite useful.)
4. Please consider supporting Ferdi!
  👉  https://github.com/sponsors/getferdi
  👉  https://opencollective.com/getferdi/donate
5. Please ensure you've completed all of the following.
- [x] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

#### Description of Change
Removed toggles around the Franz paid plans features
- serviceLimit
- planSelection
- trialStatusBar

and other Franz features that were for different tiers of subscription.

#### Motivation and Context
- Remove unnecessary processing/logic when the app is running since these features are always on for the Ferdi users equivalent to the top tier of Franz.
- Cleanup of code.
- Better maintainability
- Smaller download of the installer file (for macos x86, size of the .app went from 335 MB to 310 MB)

#### Checklist

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`$ npm run lint && npm run reformat-files && npm run manage-translations && npm run apply-branding`)
- [x] `npm test` passes
- [x] I tested/previewed my changes locally

#### Release Notes

Removed all references to Franz's paid features. Everything is available free and without ads (as before).

### CODE REVIEW

**Comment by vraravam** [comment]
This is a draft - I want to release `5.6.0` first and then merge this PR.

**Review by vantezzen — COMMENTED** [review]
Looks good so far. Great work - I didn't know that this could reduce the app size by 25MB!

**Comment by kris7t** [comment]
Haven't had the time to run this yet, but it looks really cool!

One thing to think about would be what we should do if someone logged in to Ferdi with a non-premium Franz account. Perhaps the easiest thing would be to show a banner that this is not fully supported, and the users should migrate to a Ferdi account or use Ferdi without any account instead.

**Comment by vraravam** [comment]
> Looks good so far. Great work - I didn't know that this could reduce the app size by 25MB!

Sorry @vantezzen - looks like I missed a '1'. it went from `313.5MB` to `310MB` - so, a much smaller gain :(

**Comment by vraravam** [comment]
> Haven't had the time to run this yet, but it looks really cool!
> 
> One thing to think about would be what we should do if someone logged in to Ferdi with a non-premium Franz account. Perhaps the easiest thing would be to show a banner that this is not fully supported, and the users should migrate to a Ferdi account or use Ferdi without any account instead.

Yes - that is a good idea @kris7t . Is this even supported in the current version of Ferdi? ie, if such a user logs in, even then will they not get all the benefits of the full/premium account in Ferdi? (like > 6 services, no delay, etc)?

**Comment by kris7t** [comment]
I think they'll get the full benefits of Ferdi, but that might still be surprising, since the Franz server (I think) would refuse to save things that require a premium account (more than 6 services, workspaces, spell checker settings).

**Comment by vraravam** [comment]
> I think they'll get the full benefits of Ferdi, but that might still be surprising, since the Franz server (I think) would refuse to save things that require a premium account (more than 6 services, workspaces, spell checker settings).

True - but, isn't that the current behavior as well? I mean to find out whether this behavior is because of changes in this PR or existing prior?

**Comment by vantezzen** [comment]
As far as I remember, Franz validates most premium features on the client side (like service limit, spell checker etc.) and at least ca. 1 year ago there were no such checks on the server-side (It could however be that these have since been added).
Franz's server does however not save Ferdi-specific data like Service hibernation settings as their database tables just don't have these columns.

Due to this, we should still show an info banner but most features should still work as if the user were premium.

**Comment by vraravam** [comment]
Yes - that makes sense @vantezzen - but, isn't that extraneous to this PR? If so, I will put that as an info text in the appropriate screen outside of this PR, and push those changes - they seem valid for `5.6.0` itself.

**Comment by vantezzen** [comment]
Ferdi does actually already display such a banner when switching to Franz's server: https://github.com/vraravam/ferdi/blob/77df4f03eb428ac1bf7b711f33486448ab3624bc/src/components/auth/ChangeServer.js#L105-L110
So there shouldn't be a need to modify that behaviour. Just wanted to add that info so we don't remove those info texts.

**Comment by vraravam** [comment]
> So there shouldn't be a need to modify that behaviour. Just wanted to add that info so we don't remove those info texts.

Thanks @kris7t - i haven't removed that file/changed those lines in the code. So, this behaviour should continue as before.

**Comment by vraravam** [comment]
Now that `5.6.0` has been released, we can look at merging this - please approve @vantezzen @kris7t

**Pull request merged**
