### PR TITLE
Prevent unnecessary electron popup windows for links

### LINKED ISSUE #666: Enable opening links in browser instead of internal browser
**Is your feature request related to a problem? Please describe.**
Now when I click links in Google Keep they always open in an internal browser which is useless since I don't have access to saved accounts and other features I use within my regular browser. Instead I'm forced to copy the link URL and paste it in the browser.

**Describe the solution you'd like**
Either an easy to find setting or open in browser by default

**Additional context**
I'm sure I've just missed a setting somewhere, but I wasn't able to find it in the settings window so either I'm just blind or it's not discoverable enough.

### PR DESCRIPTION
**Pull request by mahadevans87**
Prevent Default behaviour of links that are auto generated in services.

### Description

 - Remove check event.disposition !== 'new-window' so that we can handle event.preventDefault() for links with <div role="link">
  - Add event.preventDefault() in main process. event.preventDefault() does not work in renderer - Ref - [](https://github.com/electron/electron/pull/9568#issuecomment-306339926), [](https://stackoverflow.com/questions/48298364/choose-which-popups-should-be-allowed-from-webview-in-electron-app)

This fix should work the unnecessary opening of electron windows in all recipes.

### Motivation and Context

This fixes #666, #636 

### How Has This Been Tested?
This has been tested in Dev environment on Google Keep Recipe

### Screenshots (if appropriate):

ferdi_666_fix

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist:

- [x] My code follows the code style of this project (run `$ yarn lint`).

### CODE REVIEW

**Comment by mahadevans87** [comment]
@kytwb Can you please review this?

**Comment by rctneil** [comment]
Not sure if it is this causing the problem but it sounds like it could be related.

In the 5.6 beta, clicking a link opens a new Ferdi Window but when Ferdi is running in the Fullscreen Mode on MacOS the new window cannot be closed even when taken out of fullscreen mode as it has no titlebar or close controls.

**Comment by notNSANE** [comment]
this is still happening in 5.6.0-beta2 @mahadevans87 @kytwb

**Comment by ccioanca** [comment]
Can confirm, also see this happening on `5.6.0-beta2`

The workaround of `right click > Open Link` works as expected; but left click is not handled correctly.

**Comment by capoei** [comment]
same problem in gmail service

**Pull request merged**
