### PR TITLE
Upgraded various npm modules in place

### PR DESCRIPTION
**Pull request by vraravam**
### Description
Ran `npm upgrade` in place which upgraded some of the modules that are not locked to specific versions.

### Motivation and Context
General maintenance

### Checklist:

- [x] My pull request is properly named
- [x] The changes respect the code style of the project (`$ npm run lint`)
- [x] I tested/previewed my changes locally

### CODE REVIEW

**Comment by kris7t** [comment]
I merged both this and #1306 locally, and now I am getting

```
(electron) crashReporter.start is deprecated in the renderer process. Call it from the main process instead.
log @ electron/js2c/renderer_init.js:15
instrument.ts:113 Download the React DevTools for a better development experience: https://fb.me/react-devtoolsYou might need to use a local HTTP server (instead of file://): https://fb.me/react-devtools-faq
/home/kris/urandom/ferdi/node_modules/electron-is-dev/index.js:11 Uncaught TypeError: Cannot read property 'isPackaged' of undefined
    at Object.<anonymous> (/home/kris/urandom/ferdi/node_modules/electron-is-dev/index.js:11)
    at Object.<anonymous> (/home/kris/urandom/ferdi/node_modules/electron-is-dev/index.js:13)
    at Module._compile (internal/modules/cjs/loader.js:1152)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173)
    at Module.load (internal/modules/cjs/loader.js:992)
    at Module._load (internal/modules/cjs/loader.js:885)
    at Function.f._load (electron/js2c/asar_bundle.js:5)
    at Module.require (internal/modules/cjs/loader.js:1032)
    at require (internal/modules/cjs/helpers.js:72)
    at Object.<anonymous> (/home/kris/urandom/ferdi/build/environment.js:8)
    at Object.<anonymous> (/home/kris/urandom/ferdi/build/environment.js:70)
    at Module._compile (internal/modules/cjs/loader.js:1152)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173)
    at Module.load (internal/modules/cjs/loader.js:992)
    at Module._load (internal/modules/cjs/loader.js:885)
    at Function.f._load (electron/js2c/asar_bundle.js:5)
    at Module.require (internal/modules/cjs/loader.js:1032)
    at require (internal/modules/cjs/helpers.js:72)
    at Object.<anonymous> (/home/kris/urandom/ferdi/build/helpers/userAgent-helpers.js:14)
    at Object.<anonymous> (/home/kris/urandom/ferdi/build/helpers/userAgent-helpers.js:61)
    at Module._compile (internal/modules/cjs/loader.js:1152)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173)
    at Module.load (internal/modules/cjs/loader.js:992)
    at Module._load (internal/modules/cjs/loader.js:885)
    at Function.f._load (electron/js2c/asar_bundle.js:5)
    at Module.require (internal/modules/cjs/loader.js:1032)
    at require (internal/modules/cjs/helpers.js:72)
    at Object.<anonymous> (/home/kris/urandom/ferdi/build/models/Service.js:16)
    at Object.<anonymous> (/home/kris/urandom/ferdi/build/models/Service.js:627)
    at Module._compile (internal/modules/cjs/loader.js:1152)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173)
    at Module.load (internal/modules/cjs/loader.js:992)
    at Module._load (internal/modules/cjs/loader.js:885)
    at Function.f._load (electron/js2c/asar_bundle.js:5)
    at Module.require (internal/modules/cjs/loader.js:1032)
    at require (internal/modules/cjs/helpers.js:72)
    at Object.<anonymous> (/home/kris/urandom/ferdi/build/api/server/ServerApi.js:18)
    at Object.<anonymous> (/home/kris/urandom/ferdi/build/api/server/ServerApi.js:662)
    at Module._compile (internal/modules/cjs/loader.js:1152)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173)
    at Module.load (internal/modules/cjs/loader.js:992)
    at Module._load (internal/modules/cjs/loader.js:885)
    at Function.f._load (electron/js2c/asar_bundle.js:5)
    at Module.require (internal/modules/cjs/loader.js:1032)
    at require (internal/modules/cjs/helpers.js:72)
    at app.js:19
/home/kris/urandom/ferdi/node_modules/electron-is-dev/index.js:11 Uncaught TypeError: Cannot read property 'isPackaged' of undefined
    at Object.<anonymous> (/home/kris/urandom/ferdi/node_modules/electron-is-dev/index.js:11)
    at Object.<anonymous> (/home/kris/urandom/ferdi/node_modules/electron-is-dev/index.js:13)
    at Module._compile (internal/modules/cjs/loader.js:1152)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173)
    at Module.load (internal/modules/cjs/loader.js:992)
    at Module._load (internal/modules/cjs/loader.js:885)
    at Function.f._load (electron/js2c/asar_bundle.js:5)
    at Module.require (internal/modules/cjs/loader.js:1032)
    at require (internal/modules/cjs/helpers.js:72)
    at Object.<anonymous> (/home/kris/urandom/ferdi/build/environment.js:8)
    at Object.<anonymous> (/home/kris/urandom/ferdi/build/environment.js:70)
    at Module._compile (internal/modules/cjs/loader.js:1152)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173)
    at Module.load (internal/modules/cjs/loader.js:992)
    at Module._load (internal/modules/cjs/loader.js:885)
    at Function.f._load (electron/js2c/asar_bundle.js:5)
    at Module.require (internal/modules/cjs/loader.js:1032)
    at require (internal/modules/cjs/helpers.js:72)
    at index.html:18
instrument.ts:113 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
(anonymous) @ instrument.ts:113
(anonymous) @ electron/js2c/renderer_init.js:111
Promise.then (async)
warnAboutInsecureCSP @ electron/js2c/renderer_init.js:111
logSecurityWarnings @ electron/js2c/renderer_init.js:111
(anonymous) @ electron/js2c/renderer_init.js:111
instrument.ts:113 Could not connect to Sentry main process. Did you call init?
(anonymous) @ instrument.ts:113
(anonymous) @ backend.ts:121
sentryWrapped @ helpers.ts:85
setTimeout (async)
(anonymous) @ trycatch.ts:34
(anonymous) @ backend.ts:120
```

On the other hand, merging just #1306 seems to work fine.

The error might be connected to some major changes with `electron-is-dev` (see https://github.com/sindresorhus/electron-is-dev/issues/24 and https://github.com/sindresorhus/electron-is-dev/releases/tag/v2.0.0), but I don't really understand why did those bite us just now.

**Comment by vraravam** [comment]
thanks @kris7t - am running more tests now. Have marked this as draft till i figure out what's happening. In the meantime, lets please merge #1306 (which drops electron back to 11.4.3

**Comment by kris7t** [comment]
@vraravam What do you think about my alternative solution for #1306? Probably we'll still need to merge #1306 due to the Mac OS issue, but at least we can keep testing with Electron 12, too.

**Comment by vraravam** [comment]
@kris7t - for the npm modules upgrade - please pull this branch. i have removed some of the later changes and kept it to a minimum. and it works locally:
`npm i && npm run lint && npm run test && npm run build`

**Pull request merged**
